### ISSUE TITLE
[Enterprise Bot Template][TS] - dotenv files should be merged into one

### ISSUE THREAD

**Issue by awaemmanuel** [microsoft/botframework-solutions#1020]
**Is your feature request related to a problem? Please describe.**

Having multiple dotenv files for production and development is not best practice and makes it hard to maintain. 

**Describe the solution you'd like**

Looking at both files, the content is duplicated and should be merged into one. The logic in the bot code can then default to `development` when ENDPOINT is empty in the dotenv file. 

**Describe alternatives you've considered**

Currently maintain both files and can be merged. 

**Additional context**

**Comment by mlipinski** [comment]
I totally agree with this suggestion, I have 5 .bot files.  One with variables that are substituted during Azure Devops per environment.  One for dev and one for prod.  Then I have the original .bot file for both dev and prod.  Last, I have the original .bot file.  When I build locally I copy the originals into the main .bot file.  When I build in Azure DevOps I use the variables versions and rename these during the Azure devops.  This is a complete pain when deploying one code base to multiple bots in different Resource Groups.

**Comment by enzocano** [comment]
Hi @awaemmanuel and @mlipinski. Currently, we are migrating from the `.env` file implementation to a similar implementation to `C#` using `appsettings.json` files to store the keys and secrets because the `.bot` files will be deprecated. We are working on the [Virtual Assistant generator](https://github.com/Microsoft/AI/tree/4.4/templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant) and, after we finish that implementation, we are going to update the related code.

We will maintain this issue open so we can notify you when the new implementation is done.

**Comment by Dewain27** [comment]
@enzocanoo can you verify that this is still an issue?

**Comment by enzocano** [comment]
Hi @Dewain27, We finished the migration of the Virtual Assistant Sample and, currently, we are working on the YAML pipelines for the TypeScript code. However, we think that we can tackle this issue during this week.

**Comment by darrenj** [comment]
Addressed as part of the new Virtual Assistant template.
