### ISSUE TITLE
[Virtual-Assistant][TS] Bot file generated by "deploy_bot.ps1" fails to write the LUIS endpoint to file

### ISSUE THREAD

**Issue by awaemmanuel** [microsoft/botframework-solutions#1034]
## Project

**Name**: 
Virtual Assistant

**Language**: 
TypeScript

## Description

`deploy_bot.ps1` for the VA fails to write the luis endpoint details to the `.bot` file. 

## To Reproduce

1. Follow the deployment steps
1. At the intial deployment step run `pwsh.exe -ExecutionPolicy Bypass -File DeploymentScripts\deploy_bot.ps1`
1. Check the generated `.bot` file

Luis endpoint will be missing. 

```json
...
      {
            "type": "luis",
            "name": <APP_NAME>,
            "appId": <APP_ID>,
            "authoringKey": <HASHED_AUTHORING_KEY>,
            "subscriptionKey": <HASHED_SUBSCRIPTION_KEY>,
            "version": "0.1",
            "region": "westus",
            "id": "general"
        },
...
```

## Expected behavior

`.bot` should include the luis endpoint just like the enterprise template version.

**Comment by dfavretto** [comment]
Hi @awaemmanuel, can you check if you have a folder named `LocaleConfigurations` with many `.bot` files as languages you have selected to deploy? The `deploy_bot.ps1` should have added your LUIS and QnA endpoint to those `.bot` files.
This is done in this way for a cleaner and more ordered structure, separating these services in a different `.bot` file for each language you choose to deploy.

We will be updating the documentation with this information in order to prevent this kind of misunderstanding happening to anyone else, and we apologize for the inconvenient it may have caused you.

**Comment by awaemmanuel** [comment]
@dfavretto Correct I see it now. Thank you. I actually just went straight to **luis.ai** to get the name. It's in the `LocaleConfigurations` bot file. I think the documentation should be updated to reflect this updated (cleaned up) structure. It looks like a copy-paste from the enterprise bot template verison.
