### ISSUE TITLE
Virtual Assistant: for 1 participant utterance by user, VA prompts to ask if user wants to include another participant/recipient for a new meeting/email

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-solutions#1036]
## Project

**Name**: VA

**Language**: C#

## Description

When a user in their smart utterance include a/1 participant for setting up a new meeting, VA should prompt to ask if they want to add another. 

If a user sets up a new meeting/email from scratch and includes 1 participant to start with, VA should prompt to ask if they want to add another. 

If a user includes >1 participants in their request, VA **does not** have to prompt if they want to add another.  
## Expected behavior
Per default and when a user in their utterance only include 1 recipient. We do prompt to know if they want to add more.

Bot: Sure, who will join?
User: Greg Grace. 
**Bot: I have included [Greg], do you want to add another participant?
User: Yes
Bot: Who do you want to add?
User: Sam Hay
Bot: I have included [Sam], do you want to add another participant?**
_User: No
Bot: What is the subject of the event?_

+ for email prompt should include recipient instead of participant.

**Comment by darrenj** [comment]
@rng - This is a difficult one, some users expect "one shot" behaviour if they ask something like "book a meeting with Quirine tomorrow at 4pm to discuss Virtual Assistant". If we find a name then it confirms to the user and books. Prompting for extra attendees in some cases is correct but others annoying - any suggestions on how to balance this?

My leaning is towards having configuration settings to control behaviour like this because it will just depend on scenario. Thoughts?

**Comment by Quirinevwm** [comment]
Talked this over end of last week. Automotive interaction has shown that users tend to fill in participants 'as a list' since they are used to this format form 1 by 1. Agree with the extra prompting can be annoying, but not being able to add more when you are selecting contacts can feel disappointing too. The idea to prompt when only 1 participant is selected and no prompting >1 would make the difference. Your settings config to control based on the canvas/scenario would be advisable for this scenario then!
