### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by LakshmanRaja209** [microsoft/botframework-solutions#1145]
## Project

Virtual Assistant, Skills, Enterprise Bot Template, or Customer Support Template

**Language**: 

## Description
I have a Errors while building the project need help to build and test the project

## To Reproduce
Download the project and Build the Solution

## Expected behavior
Project should be build and should be able to run

## Screenshots

![image](https://user-images.githubusercontent.com/37842948/56631628-bd04ee80-6673-11e9-9804-e9a64ebc0e7e.png)

![image](https://user-images.githubusercontent.com/37842948/56631645-d148eb80-6673-11e9-9d27-19b8876f1a18.png)

## Additional context
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.	EmailSkill (Skills\EmailSkill\EmailSkill)	C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137	

For this above error I have changed the Project Build to .Net Core 2.1 later once it changed I am getting the below errors

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.Bot.Builder.Solutions 4.4.36-preview is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Bot.Builder.Solutions 4.4.36-preview supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)	AutomotiveSkill (Skills\AutomotiveSkill\AutomotiveSkill)	E:\Bot Framework\AI-master\AI-master\solutions\Virtual-Assistant\src\csharp\skills\automotiveskill\automotiveskill\AutomotiveSkill.csproj	1

**Comment by lauren-mills** [comment]
Looks like you need to update your .NET Core SDK version to 2.2 or higher. https://dotnet.microsoft.com/download

**Comment by anusharr** [comment]
You will have to change the .NET Core SDK to[ 2.2 ](https://dotnet.microsoft.com/download)or higher as the package Microsoft.Bot.Builder.Solutions 4.4.36-preview is compatible with v2.2 and not with v2.1.

**Comment by darrenj** [comment]
Let us know if this doesn't help resolve.

**Comment by samaea** [comment]
I was also faced with this issue with .NET Core SDK v2.2 installed, but noticed VS2017 did not list v2.2 as an option under "Target framework", even though “dot net —info” was reporting it as installed.

![coresdk-2 2-error-1](https://user-images.githubusercontent.com/32162601/57564705-21c88480-73a8-11e9-9160-bcba446c0b92.PNG)

Turns out on the .NET Core SDK download page, two options for 2.2 are listed (this isn't obvious at first as you may need to scroll down), one of which is compatible with VS2017 - installing that version resolved my issue. Screenshot below for context.

![coresdk-2 2-error](https://user-images.githubusercontent.com/32162601/57564703-09f10080-73a8-11e9-9a1f-b751459207f6.PNG)
