### ISSUE TITLE
TT file for Skill responses needs to handle deserialization errors gracefully

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#140]
**Description**

If a developer accidentally creates a malformed .json file (eg. POISharedResponses.de.json) the corresponding .TT file doesn't gracefully handle the exception meaning that even if one of many files is malformed no responses are available to a skill.

each file processing should be wrapped with a try/catch and tracing. This change needs to be replicated across all instances of the .tt file. Moving forward this will all be removed in favour of LG
```
 var jsonFiles = Directory.GetFiles(resDir, JsonFileName);
                foreach (var file in jsonFiles)
                {
                    var jsonData = File.ReadAllText(file);
                    var responses = JsonConvert.DeserializeObject<Dictionary<string, BotResponse>>(jsonData);
                    var key = new FileInfo(file).Name.Split(".")[1].ToLower();

                    jsonResponses.Add(key, responses);
                }
```

**To Reproduce**
1. Modify one of the response files to be malformed
2. Run the skill and no response files can be found meaning skill operation fails

**Expected behavior**
1. Dev Trace/Emulator trace to indicate a particular file has an issue
2. Skip that file and move on

**Comment by lzc850612** [comment]
I think from exception handling point of view, there's some types of exceptions we want to handle and log and swallow, and there's some types of the exceptions we want to stop the application for. I think this case should be something we have to stop the application for. If there's something wrong with the response json files, we would want the developer to look at it and stop the application. If we swallow it and keep going, there might be weird behaviors (showing response in a different language because the one for the right language doesn't exist), also it won't look severe enough so the developer wouldn't go and fix it, even with the trace message in emulator (sometimes we're not even using emulator). so i think the current behavior is correct.

**Comment by darrenj** [comment]
That's fair - as you say it could mask an issue. I would ask we wrap and throw a specific error to help the developer understand what's wrong. Right now it's very hard to understand what's happened and takes a lot of time to debug. Throwing something more direct - deserialization error occurred during XYZ Skill calendar responses, etc. etc.

**Comment by lzc850612** [comment]
Agreed. I'll make the fix.
