### ISSUE TITLE
[VA websocket] Skill invocation fail to work in Directline Speech Client

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-solutions#1420]
## Project

**Name**: 

**Language**:

**Comment by lzc850612** [comment]
The root cause of this issue is because in Speech channel, the WebSocketEnabledAdapter is using a singleton IBot instance. This will make the various components we use in the pipeline all singleton which caused the SkillWebSocketTransport issue because it's not designed to be a singleton. ABS team has agreed on fixing this on their side so waiting on that change to be out to close out this issue.
