### ISSUE TITLE
Import of Virtual Assistant Template not possible on Mac (Visual Studio Code) 

### ISSUE THREAD

**Issue by ppaltmann** [microsoft/botframework-solutions#1437]
## Project

**Name**: 
**Language**: 

## Description
Import a .vsix on Mac via Visual Studio Code fails
**extension/package.json not found inside zip.**

## To Reproduce
1. Open Visual Studio Code on Mac
2. Install from from .vsix 
3. Error: extension/package.json not found inside zip.

## Expected behavior
Installation of .vsix is successful

## Screenshots
<img width="481" alt="Screen Shot 2019-05-28 at 17 49 17" src="https://user-images.githubusercontent.com/452317/58496098-0f549600-8171-11e9-9264-9b821e32d33f.png">

**Comment by darrenj** [comment]
Unfortunately VSIX isn't supported on Visual Studio Mac or Visual Studio Code. We are working on dot net templates for Virtual Assistant to light-up vscode support. We do provide a sample project which you can clone instead: https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/csharp/Sample

**Comment by glennmusa** [comment]
@darrenj looks like there may be confusion about consuming VS Code Extensions via .vsix originating from here:
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

I assume the equivalent desired state would be something similar to [dotnet new](https://github.com/dotnet/templating)?

**Comment by darrenj** [comment]
Thanks Glen - I'll give that a try perhaps it works on Windows but suspect Mac won't be able to cradk the archive. Yes, dotnet new is the direction.

**Comment by darrenj** [comment]
I've taken a look at this, the vscode feature is a little confusing - it's referring to installing a vs code extension which is packaged inside a VSIX. An odd combination for sure - the reason this doesn't work is because the vsix doesn't have vscode extensions. We are tracking this work item with #904 which we hope to have completed in the next month - keep an eye on #904. In the meantime feel free to use the [Sample Project](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/csharp/Sample) to get you started (this is what the VSIX creates for you)

**Comment by glennmusa** [comment]
Cool, thanks for following up Darren.

**Comment by darrenj** [comment]
Work is tracked here: https://github.com/microsoft/botframework-solutions/pull/1580

If your keen there are testing instructions, they seem to work and needs build/publishing but may help unblock people.
