### ISSUE TITLE
[Android App] Application needs to be able to register as the default assistant on Android

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1445]
Application should be able to be registered as the default assistant by the user on android.

**Comment by abiemann** [comment]
I am blocked because Google's sample code is incomplete. To get the sample code, go to:
 - https://developer.android.com/training/articles/assistant#implementing_your_own_assistant
and click on
 - https://android.googlesource.com/platform/frameworks/base/+/marshmallow-release/tests/VoiceInteraction/
 - make a new project and copy the files in
 - observe that MainInteractionService class is unable to build.
