### ISSUE TITLE
Australia East Region Deployment Issues

### ISSUE THREAD

**Issue by NathanNZ** [microsoft/botframework-solutions#1454]
## Project

**Name**: Virtual Assistant Template 
**Language**: C#

## Description
When running the ".\Deployment\Scripts\deploy.ps1" script with "australiaeast" regions, the QnA Maker service fails to deploy and the Application Insights resource is created in "West US 2"

## To Reproduce
Run the deploy script using "australiaeast" for each region.

The following error will occur
! Deployment failed for resource of type Microsoft.CognitiveServices/accounts.
! Code: InvalidApiSetId.
! Message: The account type 'QnAMaker' is either invalid or unavailable in given region..

## Expected behavior
The deployment is successful, with the QnA Maker service created in the West US region. (this is currently what the Wizard through the Azure portal does). The Application Insights resource should should be in the correct region (australiaeast)

**Comment by NathanNZ** [comment]
For anyone who needs a quick workaround, the /Deployment/Resources folder has the parameters.template.json that can be modified to fix up the deployment with the following two steps.

- Set the "appInsightsLocation" variable to australiaeast, 
- Change the "Microsoft.CognitiveServices/accounts" object with the kind "QnAMaker" to have a location of "westus"


For an actual fix for this I'd suggest
- The "appInsightsLocation" variable should be set to the same location as the resource group in the deploy script
- The location for the QnA Maker should have a conditional template like the following untested snippet
`[if(equals('[parameters('qnaServiceLocation')]', 'australiaeast'), 'westus', '[parameters('qnaServiceLocation')]')] `

**Comment by lauren-mills** [comment]
Hi @NathanNZ, official Azure guidance says not to hard code any region-based logic in the templates due to ever-changing availability of services. That's why there is not more defensive logic in the template. Our recommendation around region support is to use the parameters file to customize regions.

**Comment by githubpublicconnection** [comment]
That's a good point, would be confusing if anyone was to import the template directly without knowing about that hack around. 

What would your opinion be on sitting logic in the deploy script (not the template file) and pass the region parameter for the QnA Cognitive service downstream that way?

**Comment by NathanNZ** [comment]
That's a good point, would be confusing if anyone was to import the template directly without knowing about that hack around.

What would your opinion be on sitting logic in the deploy script (not the template file) and pass the region parameter for the QnA Cognitive service downstream that way?

**Comment by lauren-mills** [comment]
If you want to add your own logic to the deploy script, that works. The scripts are really there to be customized to your needs. 

As for us adding that in ourselves, it would require us to maintain our own list of supported regions which could quickly become out-of-date. We've settled on requiring each individual dev to do their own research about the regions they want to use, and trying to make the errors helpful if the service isn't supported in the region provided.

**Comment by darrenj** [comment]
@NathanNZ - I missed the subtlety above of having to change qnaservicelocation to get westus to work. I've just debugged some further issues in europe where it was refusing to deploy and worked with the QnAMaker team. #1476 has fixes for this - turns out the core part of QnAMaker is only in westus, but all dependent services (that hold your KB) can be in your local region so we've had to (yuck) fix qnamaker to westus and use the region for the dependent resources only.

Good spot!
