### ISSUE TITLE
VA deployment script fails if working path has a space (e.g. username)

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1474]
## Project

Virtual Assistant

## Description

Issue raised by customer - likely due to the fact the path is not passed in quotes.

```
In the file path, in Windows, there is name+space+surname of the user. the space broke the command. The issue is when the deploy script call the deploy:cognitive_model.ps1
```

Likely fix is to change

```
	# Deploy cognitive models
	Invoke-Expression "$(Join-Path $PSScriptRoot 'deploy_cognitive_models.ps1') -name $($name) -luisAuthoringRegion $($luisAuthoringRegion) -luisAuthoringKey $($luisAuthoringKey) -qnaSubscriptionKey $($outputs.qnaMaker.value.key) -outFolder $($projDir) -languages `"$($languages)`""
```

to the following (note single quotes around projDir

```
	# Deploy cognitive models
	Invoke-Expression "$(Join-Path $PSScriptRoot 'deploy_cognitive_models.ps1') -name $($name) -luisAuthoringRegion $($luisAuthoringRegion) -luisAuthoringKey $($luisAuthoringKey) -qnaSubscriptionKey $($outputs.qnaMaker.value.key) -outFolder `"$($projDir)`" -languages `"$($languages)`""
```

## To Reproduce
Have a space in the working folder path.

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/58870902-f2601b80-86b8-11e9-8798-18d6bbc6b140.png)

**Comment by guru98** [comment]
Hi, i will try the fix later in the afternoon as right now I'm on the Customer site. in the meanwhile I notest that in your suggestion you have the projDir parameter  while i have Outfolder in mine. Have you a different, 
updated version of the file? here is mine in attach.
[deploy.zip](https://github.com/microsoft/botframework-solutions/files/3252525/deploy.zip)

**Comment by darrenj** [comment]
Looks like you do have scripts from a while back - we've updated a number (including the VSIX templates). I f you have an project created from an earlier version you can update scripts from these docs: https://github.com/microsoft/botframework-solutions/blob/235dc723822d655922bfe0ec9243ee3b33523cbb/docs/howto/assistant/updatedeploymentscripts.md

**Comment by guru98** [comment]
Hi Darren, i try but i have the same error. I move forward replacing $PSScriptRoot with .\deployment\scripts but i receive other errors at parsing general LU file. I think that you have to double check every path in the script.

**Comment by guru98** [comment]
Darren, an other update: i try to generate the solution in a path without space. obviusly it go forward but if you have cognitive services tools in a path with spaces you have the same issue.
The problem is that this is the default for Windows 10 installation and a lot of IT uses defaults

**Comment by guru98** [comment]
@darrenj have you seen my two pewvious posts?

**Comment by lauren-mills** [comment]
Reopening to do more testing.

**Comment by BillStrait** [comment]
I'm chiming in on this too. This is the fix I landed on.
`Invoke-Expression "$(Join-Path $PSScriptRoot 'deploy_cognitive_models.ps1') -name $($name) -luisAuthoringRegion $($luisAuthoringRegion) -luisAuthoringKey $($luisAuthoringKey) -qnaSubscriptionKey $($outputs.qnaMaker.value.key) -outFolder ``"$($projDir)``" -languages ``"$($languages)``""`
becomes this:
`Invoke-Expression "& ``"$(Join-Path $PSScriptRoot 'deploy_cognitive_models.ps1')``" -name $($name) -luisAuthoringRegion $($luisAuthoringRegion) -luisAuthoringKey $($luisAuthoringKey) -qnaSubscriptionKey $($outputs.qnaMaker.value.key) -outFolder ``"$($projDir)``" -languages ``"$($languages)``""`

Of course this needs to be done on anything that uses the `$PSScriptRoot` variable. I think, since we're already required to be in the project root folder, using `.\deployment\scripts\` is a more readable solution.

**Comment by BeigeBadger** [comment]
Has this fix been pushed to the latest version of the Virtual Assistant template? I ran into this issue today and replacing all instances of $PSScriptRoot with ".\deployment\scripts" as suggested by @BillStrait did not work.
