### ISSUE TITLE
Skill's manifestTemplate.json is not created 

### ISSUE THREAD

**Issue by jbonet07** [microsoft/botframework-solutions#1475]
## Project

**Name**: Skills
**Language**: TypeScript

## Description
After following the [Skill Creation Tutorial](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/typescript/skill.md), I get to a point where I have to check my Skill manifest but its not in the project. 

> Your newly created Skill has a basic Skill manifest file provided in the root directory (manifestTemplate.json)

## To Reproduce
Follow the Typescript Skill creation tutorial.

## Expected behavior
To have the manifestTemplate.json created in the root directory or somewhere in the project.

## Screenshots
![image](https://user-images.githubusercontent.com/36271817/58875485-f6e1ff80-86cb-11e9-9351-fbae701f605f.png)

![image](https://user-images.githubusercontent.com/36271817/58875567-2f81d900-86cc-11e9-83f5-86b67064881b.png)

## Additional context
I had no problems either creating the Skill or deploying it.

**Comment by aschemel** [comment]
I'm getting the same error over here. No manifest file present.

**Comment by Batta32** [comment]
Hi @jbonet07 , @aschemel . Thanks for contributing!
We fixed the issue of the missing `manifestTemplate` file in the #1478. Meanwhile, you can use this [manifestTemplate](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/manifestTemplate.json) file adding it in the **src folder**.

Related to the **Skill Manifest endpoint** we are still working on!

**Comment by yuuzora** [comment]
Same problem here, but even after adding the manifestTemplate.json in the src or the root of the Skill and running "npm run start again" I get the same error message.
Am I missing something obvious?

**Comment by Batta32** [comment]
Hi @Zack-Strife,

Please, update the version of your `generator-botbuilder-assistant` in order to have the latest changes:
> npm uninstall --global generator-botbuilder-assistant
npm install --global generator-botbuilder-assistant

We fixed this issue in the following PRs:

- [PR#1478](https://github.com/microsoft/botframework-solutions/pull/1478) - Adding the missing _manifestTemplate.json_ file
- [PR#1511](https://github.com/microsoft/botframework-solutions/pull/1511) - Implementing the Skill Manifest endpoint (e.g. http://localhost:3980/api/skill/manifest)
