### ISSUE TITLE
Bot always responses with "Sorry, it looks like something went wrong."

### ISSUE THREAD

**Issue by D33TW0** [microsoft/botframework-solutions#1588]
## Project

**Virtual Assistant** 

**C#** 

## Description
 I deployed the Bot to Azure and everything worked fine. Then i spammed "Hello" just to try out how the bot handles with spam and now the bot always responses with Sorry, it looks like something went wrong. (I dont know if it is even because of the spam but that would be my first guess). In the Emulator i get the output "Operation returned an invalid status code 'Forbidden'" (As it is seen on the screenshot)

## Expected behavior
 The Bot should response with "Hello."

## Screenshots

![2](https://user-images.githubusercontent.com/39704877/59675439-8d7ee800-91c5-11e9-895c-52f33c108fbb.PNG)
![1](https://user-images.githubusercontent.com/39704877/59675442-8f48ab80-91c5-11e9-94d7-abafe0da915d.PNG)

**Comment by darrenj** [comment]
If you click on the trace (Forbidden) I suspect your getting a throttling or similar issue from LUIS? Clicking on it will show the exception

**Comment by samaea** [comment]
I just ran into this issue - it appears the deployment script (deploy.ps1) populates the LUIS authoring key to be the same as the subscription key, instead of obtaining the key from the LUIS resource located in the resource group.

Noticed this behaviour in both the VA and the POI Skill.

![luiskeys](https://user-images.githubusercontent.com/32162601/59861226-4d139b80-9378-11e9-8333-216ffa740ca1.png)

**Comment by D33TW0** [comment]
![Unbenannt](https://user-images.githubusercontent.com/39704877/59914072-e21aa100-9419-11e9-92c1-83c8a1d6cad4.PNG)
Yo i dont even have the General LUIS model haha (or is this normal?)

**Comment by darrenj** [comment]
This is a known limitation of the LUIS APIs (meaning we can't set the key programatitcly) therefore we have to leave you with the starter key to ensure it works "out of box". Unfortunately at this time you'll need to go through each LUIS resource and assign the actual created endpoint key to each LUIS model and publish. Then update your cognitivemodels.json with the subscriptionKey.

We have #1453 tracking this work, we've just got some updates to APIs so will seek to get this added in.

**Comment by darrenj** [comment]
You could also experience issues when the starter key runs out of quota hence switching to the keys is important.

**Comment by D33TW0** [comment]
I redeployed the complete VA and the first "Hello" in the chat works but then every other input (even Hello again or restart the conversation) gets an Error Response - strange
![Bot-Emulator2](https://user-images.githubusercontent.com/39704877/59918115-15622d80-9424-11e9-968c-2d468230162a.png)

**Comment by darrenj** [comment]
- Can you click both trace lines and share the exceptions?
- Also confirm emulator locale is set to de-de or similar?
- Go into luis portal, browse to the dispatch model, click manage, keys and endpoints, then click the endpoint URL. add a question to the end of the URL and check you don't get an error back

**Comment by D33TW0** [comment]
- I cant reconstruct the Chat because the bot always says "Sorry, it looks like something went wrong."
(now even when i delete&redeploy everything)
![1](https://user-images.githubusercontent.com/39704877/59923023-9aecda00-9432-11e9-98c8-84b420498f45.PNG)
The first Trace
-
-
-
-
-
![2](https://user-images.githubusercontent.com/39704877/59923031-a3451500-9432-11e9-93f3-fa91c50d4d19.PNG)
The second trace
-
-
-
-
-

- Yup, the Language in the emulator is set to de-de

-I get this when i ask How old are you?
![how old are you](https://user-images.githubusercontent.com/39704877/59922883-21ed8280-9432-11e9-8724-c543c34185e9.PNG)

**Comment by darrenj** [comment]
There you go! Your out of quota on your "starter key"

## Deployment doesn't assign the newly created LUIS subscription key to the created LUIS models.

Due to a limitation with the LUIS authoring APIs the deployment script isn't able to assign the newly created LUIS subscription-key to the deployed and published LUIS models. Instead, the current workaround is to rely on the Starter Key meaning the Virtual Assistant and Skills work with no manual steps. We are working on changes to the LUIS authoring APIs to enable this to be assigned automatically.

In the meantime, you'll have to manually update the subscription key for each deployed LUIS model, train and publish. Then update the `subscriptionKey` for each LUIS model in `cognitiveModels.json` with the new subscription key. If you exhaust the quota for your LUIS key you will experience errors when invoking LUIS, updating to a subscription key will resolve this.

In the LUIS portal go through each LUIS model,  click Assign Resource and locate the appropriate subscription key and then re-publish. **You'll need to repeat this for each Dispatch and LUIS model used by your project.**

**Comment by darrenj** [comment]
Let us know if you still have any issues

**Comment by D33TW0** [comment]
> There you go! Your out of quota on your "starter key"
> 
> ## Deployment doesn't assign the newly created LUIS subscription key to the created LUIS models.
> Due to a limitation with the LUIS authoring APIs the deployment script isn't able to assign the newly created LUIS subscription-key to the deployed and published LUIS models. Instead, the current workaround is to rely on the Starter Key meaning the Virtual Assistant and Skills work with no manual steps. We are working on changes to the LUIS authoring APIs to enable this to be assigned automatically.
> 
> In the meantime, you'll have to manually update the subscription key for each deployed LUIS model, train and publish. Then update the `subscriptionKey` for each LUIS model in `cognitiveModels.json` with the new subscription key. If you exhaust the quota for your LUIS key you will experience errors when invoking LUIS, updating to a subscription key will resolve this.
> 
> In the LUIS portal go through each LUIS model, click Assign Resource and locate the appropriate subscription key and then re-publish. **You'll need to repeat this for each Dispatch and LUIS model used by your project.**

Thank you this fixed the issue!
