### ISSUE TITLE
Inputting the name of a meeting item doesn't work in calendar skill in chinese mode

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#160]
**Description**
After asking what's in my calendar, typing in the name of the meeting to show my options doesn't always work. Also, when it seems to work, it doesn't show the detail of the meeting

**To Reproduce**
Steps to reproduce the behavior

Open webchat for the bot
Ask 'what's my calendar'
The bot shows the list of meetings
Type in the name of one of the meetings

**Expected behavior**
Shows detail about the meeting

**Actual behavior**
Sometimes it doesn't seem like the bot recognizes the name of the meeting because it keeps asking which meeting i want to know more about. sometimes it just kind of ends the conversation and asks what else the bot can do for the user.

**Comment by darrenj** [comment]
it turns out this is an issue with English too. First issue is a prompt text issue - it's actually asking do you want more information. If you say "yes", it then asks you which one and you need to say first one, second one.

Can you see if that helps you move forward, if so I've fixed the response text in a branch for the LU changes.

**Comment by KayMKM** [comment]
As Darren said, you need to reply a number to choose which meeting you want. If we need show meeting detail by meeting title, it should be a feature request.
