### ISSUE TITLE
[botskills] botskills connect adding all intents from skill rather than just the ones specified in skill manifest

### ISSUE THREAD

**Issue by litofish** [microsoft/botframework-solutions#1719]
## Project

**Name**: BotSkills CLI tool

**Language**: C#

## Description
When adding a skill to an assistant using botskills connect, all the intents are added to the assistant's dispatch model rather than just the intents that are specified in the skill manifest.

## To Reproduce
In skill manifest have only one intent specified under actions. Add skill to assistant using botskills connect. All intents are added in assistant's dispatch folder.

**Comment by Batta32** [comment]
Hi @litofish,

By design, `Botskills` CLI tool takes all the intents from the `.lu` file to create the `Dispatch model`, during the connection of your _Skill_ to your _Virtual Assistant_.

The purpose of the _Virtual Assistant Dispatch_ is to have a model with the connected skills, so the dispatch knows where to send the intent, and then the related skill matches with the correct intent to execute the intent's functionality.

We took your point, and it's understandable, we are reviewing other alternatives to generate the `Dispatch model`.

**Comment by lauren-mills** [comment]
You should be able to use the --includedIntents parameter on the dispatch add command to only add the intents specified in the actions array of the manifest. When we start expanding the LUIS models to include turn n intents it'll be more important to include only the triggering intents in dispatch.
