### ISSUE TITLE
[Android App] documentation

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1754]
* Virtual Assistant App overview
* Pre-requisites to build
* Deployment/configuration instructions
* Screenshots to support
* How to run

@ryanlengel:
* Provide outline of documentation

@abiemann:
* Fill in outline with details

**Comment by abiemann** [comment]
Feedback from Darren regarding credentials:

Can we a little more specific about the configuration changes the user needs to add in their configuration file?

E.g. where to put the speech channel secret, speech configuration key, etc. If we can also align on the same naming conventions to reduce confusion that might help too. Perhaps include an excerpt of the configuration file we want them to update and guide them on the specific ones they must provide in order to be successful.
