### ISSUE TITLE
Single Sign-on via Teams

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1788]
## User Story
As ... bot user
I want ... to  automatically log into my Teams VA with my Teams credentials
so that ... I do not have to log in again with the same account.

## Acceptance Criteria 
*List your requirements.*
- [ ] User's AAD credentials should be passed to the VA to authenticate user with bot token service

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by Dewain27** [comment]
@darrenj who will be taking lead to connect with the Teams team?

**Comment by xieofxie** [comment]
Does it focus on [Silent authentication and SSO](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-aad) or [Single Sign-On SAML protocol](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol)? Since it seems that OAuth2 with an explicit dialog has worked well for bot in Teams..

**Comment by darrenj** [comment]
In motion
