### ISSUE TITLE
[POI Skill] Navigation/Routing can break the user state size limit of 2 MB in CosmosDB

### ISSUE THREAD

**Issue by h2floh** [microsoft/botframework-solutions#1864]
#### What project is affected?
POI Skill

#### What language is this in?
C# (TS may be affected too)

#### What happens?
When requesting the navigation feature of POI skill for a long route, the user/conversation state store comes to an Overflow because of the item Limit of 2MB in Cosmos DB. 

#### What are the steps to reproduce this issue?
When requesting the navigation feature of POI skill for a long route, the user/conversation state store comes to an Overflow because of the item Limit of 2MB in Cosmos DB. 

#### What were you expecting to happen?
Regardless of the route I pick no error in the backend.

#### Can you share any logs, error output, etc.?
User State JSON file screenshot:
![image](https://user-images.githubusercontent.com/29010283/61270143-b3ef6d80-a7db-11e9-8a81-8177b32cd4ad.png)

#### Any screenshots or additional context?
There are a lot of Route Direction Points stored in the conversation/user state file so that it exceeds 2MB in total.

**Comment by ryanisgrig** [comment]
This will be resolved in #1443 where the directions will not be returned.

**Comment by xieofxie** [comment]
> This will be resolved in #1443 where the directions will not be returned.

<del>Well, for single route, it could be sent directly to the user/navigation app and need not to be saved in user state. However, for multiple routes (*), they have to be saved for selection and being used in the next turn.</del>

I am also wondering if we have any design doc/future plan for handling large user state like 'developers are required to save them in another db like blob storage' or 'separate the data to multiple cosmos db records'.

<del>*: yet impossible now, since maxAlternatives is not set..</del>
