### ISSUE TITLE
"botskills refresh" should use inlineTriggerUtterances when updating

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#1872]
#### Is your feature request related to a problem? Please describe. 
Today, if you run botskills refresh, there is no way to handle the updated .lu files for different skills being in different places. There is only one "--luisFolder" parameter and it can't be automated since the path isn't in config. 

#### What is the solution you are looking for?
If `botskills refresh` used the inlineTriggerUtterances endpoint of the skills (e.g. http://bfcalendarskill.azurewebsites.net/api/skill/manifest?inlineTriggerUtterances=true) to refresh, adding the utterances to the dispatch directly, we wouldn't have to provide the .lu file location to get the latest updates.

This would enable the update_cognitive_models.ps1 script to rebuild the .dispatch file based on the config, which would help in a distributed dev environment.

#### Is there any other context you can provide?
I'm not sure what is needed to compile the utterances into a consumable format for the dispatch tool, but I think they can be parsed into a tabbed file as an input.

**Edit:** The dispatch tool can accept either a tsv file or txt file with the utterances directly in the `--filePath` parameter. 
> --filePath          [Required only if type is file] Path to tsv file containing two tab delimited fields in each line representing intent and utterance or .txt file containing one utterance on each line with the file name representing intent name

**Comment by dfavretto** [comment]
Hi @lauren-mills,

Right now we are working on implementing the `support for multilanguage skills `(#1554), which introduces some big changes on the way the Skill manifest is being consumed and processed. As soon as we finish with this feature, we'll move to implementing the consumption of `InlineTriggerUtterances` using a new option in the commands to indicate the use of this feature instead of a `.lu` file.

**Comment by ryanisgrig** [comment]
Hey @dfavretto, now that multilanguage support should be in (#2131) is this issue unblocked? Issue #1554 is still open but I believe that it just didn't auto-close from the PR.

We're looking to separate the Skills into a new repository, this is dependent on the CLI tool allowing for inline trigger utterances so that all of the existing builds don't break.

**Comment by dfavretto** [comment]
Hi @ryanlengel, indeed, the issue #1554 was solved with the PR #2131, but I see Darren already closed it.

Regarding this issue, we are starting with the implementation of InlineTriggerUtterances in the Botskills next week. We'll create an issue to track the progress for that implementation 😊
