### ISSUE TITLE
Skill template error when project name contain a dot char

### ISSUE THREAD

**Issue by ecarlesi** [microsoft/botframework-solutions#1972]
Skill template

C#

When use a project name containing a dot char the generated class is invalid.

Create a project using the Skill template and specify as name of the project "Project.Skill". Some classes will be generated with an invalid name (es. "public class Project.SkillLuis: IRecognizerConvert")

The template can replace dot char with underscore or just remove the dot char.

Compiler output:
1>------ Rebuild All started: Project: Project.Skill, Configuration: Debug Any CPU ------
1>Services\Project.SkillLuis.cs(13,25,13,26): error CS1514: { expected
1>Services\Project.SkillLuis.cs(13,25,13,26): error CS1513: } expected
1>Services\Project.SkillLuis.cs(13,25,13,26): error CS1022: Type or namespace definition, or end-of-file expected
1>Services\Project.SkillLuis.cs(13,26,13,35): error CS0116: A namespace cannot directly contain members such as fields or methods
1>Services\Project.SkillLuis.cs(13,35,13,36): error CS1022: Type or namespace definition, or end-of-file expected
1>Services\Project.SkillLuis.cs(13,37,13,55): error CS0116: A namespace cannot directly contain members such as fields or methods
1>Services\Project.SkillLuis.cs(14,5,14,6): error CS1022: Type or namespace definition, or end-of-file expected
1>Services\Project.SkillLuis.cs(64,1,64,2): error CS1022: Type or namespace definition, or end-of-file expected
1>Done building project "Project.Skill.csproj" -- FAILED.
2>------ Rebuild All started: Project: Project.Skill.Tests, Configuration: Debug Any CPU ------
2>CSC : error CS0006: Metadata file 'C:\Users\emili\source\lab\Project.Skill\Project.Skill\Project.Skill\bin\Debug\netcoreapp2.2\Project.Skill.dll' could not be found
2>Done building project "Project.Skill.Tests.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========

**Comment by lauren-mills** [comment]
From what I've found in the VS template documentation, this isn't possible in the current approach:
> The template can replace dot char with underscore or just remove the dot char.

I'm adding this to the backlog to investigate additional options.

**Comment by lauren-mills** [comment]
@ecarlesi after looking into this issue, the only solution seems to be to generalize the names of the Skill.lu files, SkillLuis.cs file, the entry in cognitivemodels.json, and the skill manifest definition in the Skill Template. This is doable, but would get confusing if you were trying to develop multiple skills and they all had the same names for services. For that reason, I am going to add a known issue in our docs to explain how to work around this issue.

What I believe is the easiest solution is to create the project as normal, then rename the SkillLuis.cs class to use an underscore instead of a '.'. Unfortunately, VS cannot do this automatically. Another option is to run the LuisGen tool, which should then generate a new SkillLuis class with the underscore.
