### ISSUE TITLE
[Point of Interest] Improve language model to capture more POI entities

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1987]
#### Is your feature request related to a problem? Please describe. 
The Point of Interest Skill can match generic entities like "coffee shop"," pharmacy", "grocery store", etc. but when it comes to displaying specific businesses it is not well trained.

#### What is the solution you are looking for?
Point of Interest LUIS app should be able to capture the POI entities a user has asked for, either by providing a greater variety of training data or introducing patterns to pick up what would come after "find XYZ"

#### Is there any other context you can provide?
Selfhost testers have filed related issues for queries like:
"Where is the nearest Lowe's"
"Where is the nearest Papa John's"

**Comment by darrenj** [comment]
@bobokids This should have been address with the change a few weeks back to ensure KEYWORD entities were used if passed? Papa John's is correctly pulled out

![image](https://user-images.githubusercontent.com/33519520/62175007-deb7e680-b2f0-11e9-8833-b2c5ef5b8787.png)

Where is the nearest lowe's doesn't pull out anything but `find me the nearest lowe's` does. So that's a training issue I think.

![image](https://user-images.githubusercontent.com/33519520/62175067-16269300-b2f1-11e9-9f07-b24113f34572.png)

Once this is fixed we should explore potential use of Bing Entity Search if nothing is found in an utterance. A quick test shows that lowe's is extracted but also nearest so need to explore that further.
