### ISSUE TITLE
error TS2305: Module '"node_modules/botbuilder-skills/lib"' has no exported member 'manifestGenerator'.

### ISSUE THREAD

**Issue by Edwardfelix08** [microsoft/botframework-solutions#2060]
#### What project is affected?
When generating an CLI for the Microsoft bot framework V4  using the "yo botbuilder-assistant:skill" from the command line for creating a custom skill  we are getting and error TS2305: Module '"node_modules/botbuilder-skills/lib"' has no exported member 'manifestGenerator'.

#### What are the steps to reproduce this issue?
Follow the document to create a custom Skill.
"https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/typescript/skill.md#create-your-skill "

**Comment by Batta32** [comment]
Hi @Edwardfelix08, thanks for reporting this issue!

We identified that some dependencies are not correctly loaded in the **latest preview versions** of `botbuilder-skills` and `botbuilder-solutions`.

In order to fix it, we are already working on a Pull Request updating the `npm-shrinkwrap.json` file.

As a workaround, you can use the [samples](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples) which contains the stable versions in the `package-lock.json` file 😊.
