### ISSUE TITLE
Az Bot authsetting creates AADv2 connection but does not populated the fields

### ISSUE THREAD

**Issue by cbtham** [microsoft/botframework-solutions#233]
**Project**
Virtual Assistant

**Description**
Using the az bot command to create authsettings, the fields are not populated correctly. No errors, creation went through. The documentation that I used is https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md on skills authentication

**To Reproduce**
1. Key in this command:- az bot authsetting create --resource-group YOUR_BOT_NAME --name YOUR_BOT_NAME --setting-name "YOUR_AUTH_CONNECTION_NAME" --client-id "YOUR_APPLICATION_ID" --client-secret "YOUR_APPLICATION_PASSWORD" --provider-scope-string "Calendars.ReadWrite Mail.Read Mail.Send Notes.ReadWrite People.Read User.Read" --service Aadv2
2. Oauth created with correct name, but client ID, client secret and tenant ID is not created properly(blanked)

**Expected behavior**
The created oauth settings supposed to have the fields populated.

**Screenshots**
https://user-images.githubusercontent.com/5702935/47987297-81f11c00-e122-11e8-9dba-592d7bac55f8.png
<!--If applicable, add screenshots to help explain your problem.--
![image](https://user-images.githubusercontent.com/5702935/47987297-81f11c00-e122-11e8-9dba-592d7bac55f8.png)
>
https://user-images.githubusercontent.com/5702935/47987297-81f11c00-e122-11e8-9dba-592d7bac55f8.png

**Additional context**
https://user-images.githubusercontent.com/5702935/47987297-81f11c00-e122-11e8-9dba-592d7bac55f8.png

**Comment by darrenj** [comment]
@cbtham Can you click Test Connection and see if it works? It would appear that the command line tools setting the values causes them to be "hidden" in the portal, confusing and I'll see if this is by design

**Comment by lauren-mills** [comment]
@cbtham I figured out the issue that caused this and update the docs with the fix

**Comment by awaemmanuel** [comment]
**Project**
Virtual Assistant

**Description**
Using the az bot command to create authsettings, I have a related issue when I try to create the AADv2 connection. It doesn't run for me. I get the error below

**To Reproduce**

1. Key in this command:- az bot authsetting create --resource-group YOUR_BOT_NAME --name YOUR_BOT_NAME --setting-name "YOUR_AUTH_CONNECTION_NAME" --client-id "YOUR_APPLICATION_ID" --client-secret "YOUR_APPLICATION_PASSWORD" --provider-scope-string "Calendars.ReadWrite Mail.Read Mail.Send Notes.ReadWrite People.Read User.Read" --service Aadv2
2. Command doesn't work. I end up with error below. 

az bot authsetting create: error: the following arguments are required: --provider-scope-string, --service
usage: az bot authsetting create [-h] [--verbose] [--debug]
                                 [--output {json,jsonc,table,tsv,yaml,none}]
                                 [--query JMESPATH] --resource-group
                                 RESOURCE_GROUP_NAME --name NAME
                                 --setting-name CONNECTION_NAME --client-id
                                 CLIENT_ID --client-secret CLIENT_SECRET
                                 --provider-scope-string SCOPES --service
                                 SERVICE_PROVIDER_NAME
                                 [--parameters PARAMETERS [PARAMETERS ...]]
                                 [--subscription _SUBSCRIPTION]

**Expected behavior**
The aadv2 connection should be created and oauth settings fields populated.

**Comment by lauren-mills** [comment]
Hi @awaemmanuel, this is likely because your client secret contains special characters that need to be escaped and it is blocking the provider-scope-string and service params. Try moving your client-secret param to the end and escaping. Here are some different escape methods for the different command line tools:

For Windows command prompt, enclose the client-secret in double quotes. e.g. ... --client-secret "!|%gr%"
For *Windows PowerShell, try passing in client-secret after the --% argument. e.g. ... --% --client-secret "!|%gr%"
For MacOS or Linux, enclose the client-secret in single quotes. e.g. ... --client-secret '!|%gr%'
