### ISSUE TITLE
Adaptive cards being cut off

### ISSUE THREAD

**Issue by chon219** [microsoft/botframework-solutions#2356]
Cards should fully render without being cut off. They appear to be stuck at some max height (see last POI's full details aren't shown). This appears to prevent actions from being visible as well.

![image](https://user-images.githubusercontent.com/946375/64751876-3b452d00-d550-11e9-97fd-e5342c1a4c2a.png)

![image](https://user-images.githubusercontent.com/946375/64751900-4e57fd00-d550-11e9-979d-b4be357b97d0.png)

**Comment by ryanisgrig** [comment]
@almedina-ms followed up with me on this issue today on the Adaptive Cards side, the fix we found before doesn't apply here because the card with the issue doesn't have an ActionSet that would actually hit the code. This appears to be a client issue with the following fix recommended:
Add a ScrollView on the client app so that the Horizontal view that is defined in `item_chat_box.xml` can be wrapped properly. The current card is rendered like
```
<HorizontalScrollView
    android:id="@+id/bot_cards"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_below="@id/bot_message"
    android:layout_alignParentStart="true"
    android:visibility="gone"
    android:paddingTop="8dp">
    <LinearLayout
        android:id="@+id/cards_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal" />
</HorizontalScrollView>
```

The card renders with as much space required to render but if the parent view doesn't provide enough space, then all elements will be rendered but some will be out of view.


Removing the blocked label so we can test with this.

**Comment by bobokids** [comment]
Close the issue for now. we will revisit the issue when we work on Android client app issue after Iron milestone.
