### ISSUE TITLE
Cannot use Direct Line Speech function

### ISSUE THREAD

**Issue by D33TW0** [microsoft/botframework-solutions#2376]
#### What project is affected?
Microsoft Virtual Assisstant (Direct Line Speech Tutorial)
#### What language is this in?
c#
#### What happens?
I get an error after executing the Program used in the Direct Line Speech Tutorial
#### What are the steps to reproduce this issue?
Follow the Tutorial and execute it with the Bot App Serivce in westeurope and speech api in westeurope

#### Any screenshots or additional context?
![Bug](https://user-images.githubusercontent.com/39704877/64973750-da995580-d8ab-11e9-98bd-a5116a229aeb.png)

**Comment by darrenj** [comment]
Hi Daniel,

I suspect this might be because you don't have "developer mode" enabled on your Windows PC? See [here](https://social.msdn.microsoft.com/Forums/en-US/913aae0d-c0e1-4c52-84c8-abc881f37bc0/failed-to-connect-to-device-127001-using-universal-authentication).

My first thought was it was trying to deploy to another device but 127.0.0.1 is localhost so I suspect it's developer mode on your PC?

Alternatively, relatively new there is an example test tool for DIrect-Line Speech which you can find [here](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client) and there is a release you can use rather than build.

Let me know if that helps? I can update the docs to clarify that for Windows Apps and point at the new test tool.

**Comment by D33TW0** [comment]
Heyho Darren,
my developer-mode is turned on - hm.

Could it be, that it is happening because all of my services are located in westeurope?
(I mean you even commented in the code that westeus2 is currently only supported,
but i have a policy on that says im only allowed to create services in europe rip) ^^

**Comment by darrenj** [comment]
WestEurope may be fine as they have now rolled out (since the doc was written). This is actually an error around the app launching so it's not getting that far as of yet.

I suspect it's trying to use an emulator image on your machine, can you click the arrow shown below and choose local machine not device (emulator)?

![image](https://user-images.githubusercontent.com/33519520/65162635-67e4c300-d9ee-11e9-8a3b-34328c986c56.png)

**Comment by D33TW0** [comment]
Aha! That was it! I was playing a bit with the HoloLens and had the wrong Target Device selected.

But now i get an Websocket Authentication Error (Im still new in this topic, sorry for asking for help that much)

![error-Websocket](https://user-images.githubusercontent.com/39704877/65170028-19641280-da48-11e9-95a7-58451cf901fb.PNG)

I exactly copied the keys and secrets from:
![keys2](https://user-images.githubusercontent.com/39704877/65170089-37ca0e00-da48-11e9-91f2-e37615e8150a.png)

And my Websocket settings (if this has to do something with that):
![Websocket](https://user-images.githubusercontent.com/39704877/65170154-55977300-da48-11e9-87bc-8b54c7ca608c.PNG)

I hope this helps :-)

**Comment by darrenj** [comment]
Odd - to help me test a theory could you try:
- Updating CognitiveServices.Speech nuget in the project to the latest, as they've updated to new regions perhaps there's a change needed there?
- Try the newer test tool: https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client to check you can repro with that.

Thanks

**Comment by D33TW0** [comment]
Hm im getting namespace-Errors after updating the CognitiveServices.Speech nuget.

But the newer Tools are working without problems, strange.
I guess i will just play a bit with these tools to try out more

Thanks for the infos!

**Comment by darrenj** [comment]
Great, just to confirm the direct line speech client worked for you and you have speech working? I’ll get the tutorial updated to use this which simplifies getting started now. Re-open if you run into anything else on this.
