### ISSUE TITLE
[VA] Pass help to skill when skill is active

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2391]
## User Story
As ... a user
I want ... to show the help of skill instead of va
so that ... I can get contextual help for the skill I am in.

## Acceptance Criteria 
*List your requirements.*
- [x] When skill is active, and user triggers "help" intent, the skill should receive the activity and have a chance to respond.
- [ ] If skill does not handle the intent (i.e. triggers "None" intent) the VA should be notified to handle the intent.

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
- This will require the OnInterrupt handler in VA to call continue dialog if a skill is active. Meaning it needs to know if a skill is active.
- Need mechanism for passing an unknown intent back to VA from Skill.

**Comment by lauren-mills** [comment]
This scenario will be enabled with Adaptive Dialogs. Should decide whether or not it is worth investment today.

**Comment by amistry79** [comment]
I am facing the same issue... when the user asks help in the middle of skill waterfall dialog then VA interrupter help dialog has been processed rather than skill interrupter help dialog... This is worth the investment because skill knows which help response should be given by skill bot and not the VA. This leads to poor conversational experience since VA does not know what help has been asked... Currently, skills implementation act as a dialog rather than skill bot. 

![image](https://user-images.githubusercontent.com/3864971/65769642-ab0f0680-e151-11e9-9333-5d0f6a53f4ff.png)

Here when user ask help then I would like to start the help dialog from skill and provide the help for parts lookup steps.

**Comment by lauren-mills** [comment]
Hi @amistry79 this logic can be customized to your scenario in the OnInterruptAsync handler of the VA main dialog. If you want to let your skills handle the help interruption, you’ll need to check if the dc.ActiveDialog.Id is equal to the id of a skill from your skills.json file, and if so, return InterruptionAction.NoAction. That should give the behavior you want. 

This issue is tracking a bigger design question of whether we want to add that behavior into the template by default, but it’s written so you can customize for your needs. Thanks!
