### ISSUE TITLE
Error: The given key 'zh' was not present in the dictionary

### ISSUE THREAD

**Issue by kelvin7070** [microsoft/botframework-solutions#2448]
#### What project is affected?
Virtual assistant
#### What language is this in?
C#
#### What happens?
I followed the tutorial and built a VA template that could run perfectly on local bot emulator. But when deployed to Azure, it throws `Exception: System.Collections.Generic.KeyNotFoundException. The given key 'zh' was not present in the dictionary.` 
I then deleted the 'zh' in library LUIS/QnA  and deployed again -->still failed.....

The strange thing is that if I changed the region l format to English-US in azure portal settings, the bot could function normally.

Where should I add the locale to fix the language support problem?
Thanks!!

#### What were you expecting to happen?
I supposed virtual assistant could support Chinese?
#### Can you share any logs, error output, etc.?
[call stack.txt](https://github.com/microsoft/botframework-solutions/files/3660874/call.stack.txt)
![image](https://user-images.githubusercontent.com/44172664/65742004-e9d89880-e120-11e9-9948-b92b7b48a33b.png)

Failed method | Forky.Dialogs.MainDialog+<OnInterruptDialogAsync>d__12.MoveNext
-- | --

**Comment by xieofxie** [comment]
Hi, VA supports multiple languages. But if you don't provide, it will throw this exception due to [here](https://github.com/microsoft/botframework-solutions/blob/5eb914c3b6c8849734bd59dbe899cb603a6a9934/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs#L82) or [here](https://github.com/microsoft/botframework-solutions/blob/5eb914c3b6c8849734bd59dbe899cb603a6a9934/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs#L302) alike.

You could modify the code so that no matter what locale client uses, bot will use en;
Or deploy zh for VA like ```Deployment/Scripts/deploy.ps1 -languages en-us,zh-cn```.

**Comment by lauren-mills** [comment]
Hi @kelvin7070 can you confirm that you deployed your cognitive models for zh-cn? You can run the following script to deploy just your zh language models:
```
.\Deployment\Scripts\deploy_cognitive_models.ps1 -languages "zh-cn"
```

If you have already deployed your zh cognitive models, can you verify that you are able to see the zh responses in the emulator when you set your locale in the emulator settings?
![image](https://user-images.githubusercontent.com/27976702/65792420-8fd3d500-e118-11e9-94e5-2194805941a9.png)

**Comment by kelvin7070** [comment]
Thanks for the help. I ve added the locale to fix it.
