### ISSUE TITLE
[POI] Fallback location matching needs refinement

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2475]
#### What project is affected?
Point of Interest Skill

#### What language is this in?
C#

#### What happens?
When a user asks for a POI without providing a location event, the skill prompts a user to where they currently are. If the user is in Seattle, POI returns asking if they mean Seattle, Washington or Guadalajara, Mexico. If this happens for one city I assume it will occur for others.

I believe this is due to an underlying problem with the fuzzy search against Azure Maps API, please validate and investigate if there is a better endpoint to validate a user's current location. If so, implement the better option.

#### What are the steps to reproduce this issue?
```
user: find a coffee shop
bot: where are you located?
user: seattle
bot: which one?
[attachment: adaptive card showing both Seattle, WA and Guadalajara, MX]
```

#### What were you expecting to happen?
Only Seattle should be returned

#### Can you share any logs, error output, etc.?
n/a

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/43043272/66143351-debbb780-e5bb-11e9-886c-e9b51c8c1499.png)

**Comment by xieofxie** [comment]
Hi, @ryanlengel 

Guadalajara has "municipalitySubdivision": "Seattle, Zapopan" and "score": 2.17681 (in comparison, Seattle, WA has score 2.55077 and Guadalajara is in 3rd place). It is not a bad result for api.

I suggest two ways to fix it (yet neither is optimal):
* Use countrySet to limit results in only several English-culture countries
* Make it more verbose for [AddressAlternative](https://github.com/microsoft/botframework-solutions/blob/e287e34f4aca5d1f7ba55168e8893c32be571a11/skills/csharp/pointofinterestskill/Models/PointofInterestModel.cs#L59) so that Seattle, Zapopan is shown in the address line

**Comment by ryanisgrig** [comment]
@xieofxie I believe we used to have the countrySet parameter set but reverted that - but it was based on using the locale so it didn't make sense if a user was in the UK and using "en-us"
If we can extract the country from the location event, it would be good to use that

**Comment by xieofxie** [comment]
@ryanlengel  It happened when the user's location is unknown, so I make AddressAlternative more verbose like shown below.

To ensure everything else is searched nearby, parking also requires current location as others. Pr is here https://github.com/microsoft/botframework-solutions/pull/2694

![image](https://user-images.githubusercontent.com/2876650/68736888-da53d700-061c-11ea-927c-3775e483b570.png)
