### ISSUE TITLE
Getting a "Parsing Error" at updating the cognitive Models

### ISSUE THREAD

**Issue by D33TW0** [microsoft/botframework-solutions#2689]
#### What project is affected?
Microsoft VA
#### What language is this in?
Powershell
#### What happens?
when i update the KB and dispatch files via
-> .\Deployment\Scripts\update_cognitive_models.ps1 -RemoteToLocal

#### What are the steps to reproduce this issue?
Follow the steps at 

https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/

1:1.
#### What were you expecting to happen?
no Errors :-)
#### Can you share any logs, error output, etc.?
(in the screenshot)
#### Any screenshots or additional context?
![ergtergergsergserg](https://user-images.githubusercontent.com/39704877/68705504-7f739e80-058e-11ea-88b4-59972eae5fd2.PNG)

**Comment by xieofxie** [comment]
@danieldangler I tried wrong config file or empty luis app, none of them reproduce your situation. Do you add some special character in your luis app?
Maybe you could try to add the following lines to see the result of `luis export`:
![image](https://user-images.githubusercontent.com/2876650/68731375-cd2dec80-060a-11ea-8462-c2fac6c65ccb.png)

**Comment by D33TW0** [comment]
These are the steps i did:
(My goal was to connect a new KnowledgeBase)
1. I created a new KnowledgeBase via the Browser, added one QnA-Pair, trained and published it.
2. I added the KB-Information in cognitivemodels.js
3. I went to my project directory and called the command:
 ->  ./Deployment/Scripts/update_cognitive_models.ps1 -RemoteToLocal
(FYI. I changed nothing in the Script, i`ve set the bot to german)
4. I added the KB in maindialog.cs

The problem is that nothing changes in the webinterface of LUIS.

I hope you can help me out with that :-)


ps. i tried to insert the four lines of code inside the Script but nothing happens. It just lists all of my Intents/utterances

**Comment by xieofxie** [comment]
@danieldangler maybe it is caused by encoding. You could try run `$OutputEncoding = [Console]::OutputEncoding` before running the script.

**Comment by D33TW0** [comment]
@xieofxie sadly this wont help.

I searched a bit more in the Issue Tab and found another User with the same (or similar) problem in 
#1430 https://github.com/microsoft/botframework-solutions/issues/1430
(But i dont get the Error with an invalid Subscription Key etc. by the way)

Could this be a region Problem?

UPDATE: If i change something in the KnowledgeBase and execute the command to update my cognitivemodels, LUIS is getting updated aswell, but inside the chat i get a Error if i want to ask a question from the connected KB. Strange strange strange.

**Comment by dmvtech** [comment]
What version of the tools are you running? Specifically dispatch, but also luis (run `dispatch-v`) and other tools would be good to know.

What OS are you running on?

**Comment by xieofxie** [comment]
Hi @danieldangler since **General** is also working wrongly, I would suggest a tedious way to check it..

![image](https://user-images.githubusercontent.com/2876650/68911595-810cb480-0790-11ea-903a-ee9dca9925ae.png)

It happens [here](https://github.com/microsoft/botframework-solutions/blob/48761068093c4a9fe207731077ccfcb1a14a189a/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1#L44), so first, check out the output of first part whether it is a valid json (same as General.luis when you deploy):
```
luis export version --appId $luisApp.appId --versionId $luisApp.version --region $luisApp.authoringRegion --authoringKey $luisApp.authoringKey
```
Then save it to file via
```
luis export version --appId $luisApp.appId --versionId $luisApp.version --region $luisApp.authoringRegion --authoringKey $luisApp.authoringKey | Out-File temp.json -Encoding OEM
```
 (or any of the [encoding](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-6) until it looks right). They may be different because console and Out-File use different encodings.

Last refresh it to see if it could be refreshed as the original General.lu.
```
ludown refresh -i temp.json -n "$($luisApp.id).lu"
```

If any of these steps could not be right, please report the locale of General you used and your system language region.

**Comment by jason-hunt** [comment]
Same exact issue here.

**Comment by jason-hunt** [comment]
The ludown refresh doesn't work for me.  If I export a QNA Kb for example, to JSON:

qnamaker export kb --environment Prod --kbId **** --subscriptionKey **** | Out-File chitchattemp.json -Encoding OEM

The JSON file looks great.  But then I do:
ludown refresh -i chitchattemp.json -n "Chitchat.lu"

The .lu file looks like this:

> ! Automatically generated by [LUDown CLI](https://github.com/Microsoft/botbuilder-tools/tree/master/Ludown), Sat Nov 16 2019 14:35:09 GMT-0700 (Mountain Standard Time)

> ! Source LUIS JSON file: chitchattemp.json

> ! Source QnA TSV file: Not Specified

> ! Source QnA Alterations file: Not Specified


> # Intent definitions

**Comment by jason-hunt** [comment]
> Same exact issue here.

I got around this for now by changing the script to output to JSON files in a temp directory and then calling ludown refresh on them, instead of reading from stdin.

**Comment by lucascrandle** [comment]
I am also having the same issue with Luis and Qna files. @jason-hunt I also found that outputting to a temporary json file worked.

**Comment by lauren-mills** [comment]
I have updated the update_cognitive_models script in the VA template to resolve this issue. You can find it here: https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1

**Comment by lucascrandle** [comment]
@lauren-mills Thanks for updating the script.
As a sidenote I also have to edit the exported json file created because the depreciation error for the tools is added to the top of the file. Ex:


```
-----------------------------------------------------------
 NOTICE:
 This tool has been deprecated.
 All functionality was ported over to the new BF CLI.
 To learn more visit https://aka.ms/NewBFCLI
-----------------------------------------------------------


  "qnaDocuments": [
    {
      "id": 1,
```
This causes the ludown refresh command to fail parsing the json. I only have this problem for the qna maker export and not the luis one. 
(This depreciation error is also kind of annoying because the new bf tool has not implemented an export command yet, unless I'm not looking in the right place?)

**Comment by D33TW0** [comment]
Ah perfect! this works for me. Thank you :)

**Comment by dmvtech** [comment]
Looks like the removal for qnamaker is in the works: https://github.com/microsoft/botbuilder-tools/commit/c61cb62e7b2e02be3520e854102b477ec5c8856f

**Comment by SreekanthOAuth** [comment]
@dmvtech , Tried based on the above link and now getting below exception,

Sorry, error parsing file as QnA JSON: D:\Test-Chatbot\test-new\test\src\virtualAssistant\deployment\scripts\..\resources\QnA\en\myskill.qna
Stopping further processing.

Could you please look into it.

Thanks,
Sreekanth
