### ISSUE TITLE
OnTurnError is not getting called in VA

### ISSUE THREAD

**Issue by YammanureSreekanth** [microsoft/botframework-solutions#2766]
#### What project is affected?

Virtual Assistant

#### What language is this in?

Typescript

#### What happens?

Below code is not been called on errors. This can be found in defaultAdapter.ts

https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/adapters/defaultAdapter.ts

` this.onTurnError = async (context: TurnContext, error: Error): Promise<void> => {
            console.log('defaultAdapter.onTurnError: ===>', error);
            await context.sendActivity({
                type: ActivityTypes.Trace,
                text: error.message
            });
            await context.sendActivity({
                type: ActivityTypes.Trace,
                text: error.stack
            });
            await context.sendActivity(i18next.t('main.error'));
            telemetryClient.trackException({ exception: error });
        };`

#### What are the steps to reproduce this issue?

Create a Virtual Assistant and throw an explicit error.

#### What were you expecting to happen?
This should be called on errors which are not been handled. For example, if there is a path issue, or LUISservice or QnA Service not found etc..

#### Can you share any logs, error output, etc.?
No.

**Comment by Batta32** [comment]
Hi @SreekanthOAuth, we are validating some scenarios to check that behavior you mentioned. We will get back to you later.

**Comment by Batta32** [comment]
Hi @SreekanthOAuth, we managed to reproduce the scenario that you mentioned.

We identified that the `onTurnError` event is not executed when the `ShowTypingMiddleware` is enabled in the `DefaultAdapter`. As a **workaround** you can remove that middleware.

Hope this helps you 😊. We will be checking the differences of the `ShowTypingMiddleware's` implementation and we will get back to you later.

### Additional Context
_ShowTypingMiddleware disabled in DefaultAdapter_
![image](https://user-images.githubusercontent.com/11904023/69830479-c3f47080-1203-11ea-9c44-66b2d7192916.png)

_OnTurnError() event executed when an error raised_
![image](https://user-images.githubusercontent.com/11904023/69830490-ca82e800-1203-11ea-8fd9-485a4363a133.png)

**Comment by YammanureSreekanth** [comment]
After commenting, this is been called. But the conversation is not ending. Can you please check this as well.

Thanks,
Sreekanth

**Comment by Batta32** [comment]
We identified the following related issues of [botbuilder-js](https://github.com/microsoft/botbuilder-js) repository explaining the reason that the `ShowTypingMiddleware` **is not propagating** the error to the adapter that fires the `onTurnError` handler function.
	• microsoft/botbuilder-js#726 - ShowTypingMiddleware suppresses errors and does not allow adapter.onTurnError to handle them
	• microsoft/botbuilder-js#1170 -ShowTypingMiddleware provoke silent error behaviour
	
@darrenj - as this issue is related to the implementation of the [ShowTypingMiddleware](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/showTypingMiddleware.ts) of `botbuilder-js`. Should we **transfer** the issue to the botbuilder-js repository?

@SreekanthOAuth - we couldn't reproduce the scenario that the dialog is not ending, so I need you to give me a full overview of what you're doing in order to figure out what's wrong.
1. Can you share the entire repro steps?
1. Are you using the [sample-assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant) of _master_ branch?

**Comment by YammanureSreekanth** [comment]
@Batta32 , thanks for the info.

In our case, we have custom skills. So, when the intent goes to skill from VA if any error occurred in skill, getting the error from OnTurnError (from skill level) to the user. But it's not coming back to VA. In this case, if we request the different utterance, it starts directly from there in skill, not from VA.
So meaning, the conversation is not getting ended.

Yes followed the same repo to create the VA. 
And followed below link to create a custom skill
[custom skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill)

**Comment by darrenj** [comment]
> We identified the following related issues of [botbuilder-js](https://github.com/microsoft/botbuilder-js) repository explaining the reason that the `ShowTypingMiddleware` **is not propagating** the error to the adapter that fires the `onTurnError` handler function.
> • [microsoft/botbuilder-js#726](https://github.com/microsoft/botbuilder-js/issues/726) - ShowTypingMiddleware suppresses errors and does not allow adapter.onTurnError to handle them
> • [microsoft/botbuilder-js#1170](https://github.com/microsoft/botbuilder-js/issues/1170) -ShowTypingMiddleware provoke silent error behaviour
> 
> @darrenj - as this issue is related to the implementation of the [ShowTypingMiddleware](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/showTypingMiddleware.ts) of `botbuilder-js`. Should we **transfer** the issue to the botbuilder-js repository?
> 
> @SreekanthOAuth - we couldn't reproduce the scenario that the dialog is not ending, so I need you to give me a full overview of what you're doing in order to figure out what's wrong.
> 
> 1. Can you share the entire repro steps?
> 2. Are you using the [sample-assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant) of _master_ branch?

Thanks - I've raised with the botbuilder JS team as I don't think ithis is by design. Will report back, we should keep the issue here and take a look at the end of conversation aspect.

**Comment by Batta32** [comment]
Hi @SreekanthOAuth, we managed to reproduce the scenario of the end of conversation.

We noticed that the conversation **is not ending** when an error is raised in the Skill's side, in C# and in TypeScript as well. We are analyzing some alternatives and we will get back to you later 😊.

Also, we noticed that this scenario is happening regardless the `showTypingMiddleware` is commented or not. Can you verify this?

**Comment by amistry79** [comment]
Martin,

Yes, This scenario is happening regardless of showTypingMiddleware is
commented or not.

Thanks,
Amit Mistry

**Comment by Batta32** [comment]
Hi @SreekanthOAuth, @amistry79, we created the Pull Request #2800 which solves the end of conversation aspect!

As the [MainDialog](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/dialogs/mainDialog.ts#L41) of the Skill extends to [RouterDialog](https://github.com/microsoft/botframework-solutions/blob/master/sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialog.ts), we should manage the `onContinueDialog` event in order to handle the errors and finish the executed dialog without saving the last conversation's state.

Also, we identified the issue #1589 (OnTurnError function inside DefaultAdapter doesn't end the current dialog) which is similar and contains a workaround for your scenario.
To accomplish this, you should create a base dialog, in your solution, to be inherited directly from the MainDialog of your Skill and manage the `onContinueDialog` event ending the executed dialog.
See this [example](https://github.com/microsoft/botframework-solutions/issues/1589#issuecomment-504716266).

Hope this helps you 😊.
