### ISSUE TITLE
[Doc] Instruction on how to change the personality chat dataset included in VA template

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#2788]
## User Story
As ...a virtual assistant developer using virtual assistant template and hospitality assistant solution accelerator or enterprise assistant solution accelerator 
I want ...to know how to change to a different personality chat dataset 
so that ...I am not stuck with the default personality chat dataset included

## Acceptance Criteria 
*List your requirements.*
- [ ] Documentation on how to change to other personality datasets (different personality in different languages) in Virtual Assistant template or enterprise/hospitality assistant sample 
https://github.com/Microsoft/BotBuilder-PersonalityChat/tree/master/CSharp/Datasets

**Comment by lauren-mills** [comment]
We already include a section in the update tutorial on where to find these datasets and how to change them. Please take a look and make and changes you need: https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/

**Comment by darrenj** [comment]
We should add the steps for `qnamaker replace` to simplify this?

**Comment by lauren-mills** [comment]
@darrenj - this is not possible, because the datasets are not provided in a consumable format for the qna cli

**Comment by lauren-mills** [comment]
This is not something that will be simple to automate without writing a custom tool (see PR above) because the datasets are only provided in TSV today, but the qnamaker CLI tool only supports json. Our team should not be responsible for maintaining code to convert these datasets to json. I've raised the link issue above requesting different formats

@elaine-chang - please followup with the QnA Maker and/or botframework-cli team to further this request.
