### ISSUE TITLE
Bot created from Virtual Assistant Template is not working - Failed to send activity. Bot returned an error

### ISSUE THREAD

**Issue by mohandivraniya** [microsoft/botframework-solutions#2887]
#### What project is affected?
Virtual Assistant Template
#### What language is this in?
C#
#### What happens?
When you send any message to bot, it responds with a generic error message: Failed to send activity. Bot returned an error.
#### What are the steps to reproduce this issue?
Download virtual assistant template
Install all required prerequsites
Create a new project using template
Create LUIS authoring key
Create app registration and get the password
Deploy bot using Deploy.ps1 command
Got to Azure, Web app bot, Test in Web Chat, type a message and send it
#### What were you expecting to happen?
Bot should respond with OnBoarding dialogue OR greeting
#### Can you share any logs, error output, etc.?
I see following request URL in network tab and then error in response:

https://webchat.botframework.com/v3/directline/conversations/45JbKfBGMWBKdlXUTNvReb-f/activities
 {
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot returned an error"
  },
  "httpStatusCode": 500
}
#### Any screenshots or additional context?
![TestInWebChatErrorMessage](https://user-images.githubusercontent.com/14078123/72505993-ed5f6f00-3838-11ea-99f5-7b15f5fd9446.png)

**Comment by xieofxie** [comment]
Hi, @mohandivraniya could your bot run correctly in local? For example, via [Emulator](https://github.com/microsoft/BotFramework-Emulator/wiki/Getting-Started)

If so, what about connecting the created `App Service`? It should be url like `https://*.azurewebsites.net/api/messages`

**Comment by mohandivraniya** [comment]
Thank you for debugging hints @xieofxie.
I tried, however, it throws below strange error when I restart the conversation (I am not even sending any message to bot API):
**The bot's Microsoft App ID or Microsoft App Password is incorrect.**

I double checked to make sure that the values I am providing for Microsoft App Id and Password are correct. 

![MicrosoftAppIdOrPasswordAreInvalid](https://user-images.githubusercontent.com/14078123/72514225-3538c300-3846-11ea-9392-cd66a3e54fe1.png)

**Comment by xieofxie** [comment]
@mohandivraniya Basically, the ones provided to Emulator should be same as microsoftAppId, microsoftAppPassword in your bot's appsettings.json. And they should exist in your azure's `App registrations`.

However, one can't view existing pw in `App registrations`, maybe you could create a new password to see if it works.

**Comment by rvallireply** [comment]
Same here, I have a Virtual Assistant that was working on WestEurope, but since yesterday isn't working anymore, not from Emulator neither from Azure Webchat Test, it simply doesn't respond.

In Application Insights I see 404 errors for 
https://botname-suffix.azurewebsites.net/api/messages

So I tried deploy a new fresh VA from the VS template and the deploy script gives me an error while validating Azure resources:
```

{
  "error": {
    "code": "InvalidTemplateDeployment",
    "details": [
      {
        "code": "ValidationForResourceFailed",
        "details": [
          {
            "code": "ServerFarmNotFound",
            "details": null,
            "message": "The specified app service plan was not found.",
            "target": null
          }
        ],
        "message": "Validation failed for a resource. Check 'Error.Details[0]' for more information.",
        "target": null
      }
    ],
    "message": "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx'. See inner errors for details.",
    "target": null
  },
  "properties": null
}

```
I checked Azure Status for West Europe but everything looks green...

**Comment by rvallireply** [comment]
**Update**: The bot uses also a Telegram channel and that seems to work. Webchat and Emulator are not.

**Comment by mohandivraniya** [comment]
@xieofxie , Yes, I know. I have verified that they are same. I also tried to delete and re-create the app registration and used updated values, however, none of those things have worked. I am starting to think something has changed on Azure Web App Bot and that is breaking the bot now. Curious to see updates from template team.

**Comment by iMicknl** [comment]
Same issue here, can not deploy the VA template due to `ServerFarmNotFound`. Possibly related issue https://github.com/MicrosoftDocs/azure-docs/issues/43536 & https://github.com/microsoft/botframework-solutions/issues/2762.

It looks like [this fix](https://github.com/microsoft/botframework-solutions/issues/2762#issuecomment-570639440) is working for `westus` & `northeurope`.

**Comment by rvallireply** [comment]
> It looks like [this fix](https://github.com/microsoft/botframework-solutions/issues/2762#issuecomment-570639440) is working for `westus` & `northeurope`.

The fix is working for `westeurope `too, thank you.

**Comment by xieofxie** [comment]
@mohandivraniya that's weird.. I just tried Bot Channels Registration and Web App Bot and they both worked. They are in global location by default.

The error in emulator will be shown when emulator couldn't get the token with provided id/pw.
If you are familiar with Postman, you could try to get token directly to see if it works:
![image](https://user-images.githubusercontent.com/2876650/72581084-15260400-3919-11ea-8512-f37ee6412d56.png)

**Comment by mohandivraniya** [comment]
@xieofxie 
I updated boframework.com with my tenant id in request url and tried in Postman. It works there and I am able to get access token. Still don't know what is wrong in web chat or emulator? 
Any other troubleshooting tips? Can region be a problem? I have web app bot in global location and other resources in West US. I had created resource group and LUIS authoring key in West US. I am not sure why web app bot is created in global location?

**Comment by xieofxie** [comment]
@mohandivraniya I don't know why it is `global` either..

After some tests, I don't think this error `The bot's Microsoft App ID or Microsoft App Password is incorrect.` will be caused by locations problems. I could reproduce this when I start the emulator, enter the host 'http://localhost:3978/api/messages' with wrong id/pw.

And if I leave id/pw empty, emulator should behave like this (a 401 with no error instead):
![image](https://user-images.githubusercontent.com/2876650/72598581-08220880-394b-11ea-86b1-52b784368b46.png)

But since your Postman could retrieve token correctly, I guess your emulator's network is blocked? So it could not get the token.

**Comment by xieofxie** [comment]
@mohandivraniya Just received a fix for a similar issue: `Make sure that the service principal/app can be used by multiple organizations.  Should be in the authorization page of the app.` Hope this helps

**Comment by mohandivraniya** [comment]
Hi, @xieofxie ,

That worked !!

I changed the supported account types to Multitenant and it is working both from web chat and emulator. The documentation at (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0&tabs=aadv1#register-an-application-in-azure-ad) should be updated to reflect this.
