### ISSUE TITLE
Typescript: Local Timestamp overwritten in parse request

### ISSUE THREAD

**Issue by tommyJimmy87** [microsoft/botframework-solutions#2903]
#### What project is affected?
Skills and VA
#### What language is this in?
Typescript
#### What happens?
When we send messages from different timezones the localTimezone is overwritten every time with the Local Server Timezone and we lose the User's Timezone.
#### What are the steps to reproduce this issue?
Try to send a message from a client in a Timezone and receive the message from a different timezone of the client.
#### What were you expecting to happen?
At least to have in the context the user timezone
#### Can you share any logs, error output, etc.?

This happens in the `BotFrameworkAdapter`, during the `processActivity` method and the `parseRequest` function.

```if (typeof activity.localTimestamp === 'string') { activity.localTimestamp = new Date(activity.localTimestamp); }```

**Comment by VictorGrycuk** [comment]
Hi @tommyJimmy87! Thanks for reporting the issue! 

We reproduced the issue and we would like to validate with you the repro steps that we followed to accomplish this. Also, we will continue reproducing the issue using a C# bot in order to compare the implementations and find the next steps to solve the issue.

### Repro Steps
Using the TypeScript [Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant)

1. Go to the Virtual Assistant's folder
2. Install the dependencies with `npm install`
3. Compile the solution with `npm run build`
4. Deploy the Virtual Assistant using the following command:

```bash
pwsh.exe -File deployment\scripts\deploy.ps1 -name "<BOT_NAME>" -location "<LOCATION>" -appId "<APP_ID>" -appPassword "<APP_PASSWORD>" -luisAuthoringKey "<LUIS_AUTHORING_KEY>" -luisAuthoringRegion "<LUIS_AUTHORING_REGION>"
```

5. Open the **Bot Framework Emulator** and configure it to connect the Virtual Assistant running locally
![image](https://user-images.githubusercontent.com/39467613/72924263-66762f00-3d2f-11ea-8e7b-e803ad2d5f09.png)

6. Set a breakpoint in the line 1004 of **botFrameworkAdapter.ts** inside of **Botbuilder** library
![image](https://user-images.githubusercontent.com/39467613/72924350-87d71b00-3d2f-11ea-97f1-84fb8a537d0a.png)

7. Change the `System Time zone` to a different one (e.g. UTC+03:00 Minsk)
![image](https://user-images.githubusercontent.com/39467613/72924376-97566400-3d2f-11ea-800a-8a4362761dfc.png)

8. Debug the Virtual Assistant
9. Start the chat with the Virtual Assistant using the emulator
10. The execution will stop at the breakpoint. The `activity.localTimestamp` will show the datetime with the **previous Local Server Timezone**
![image](https://user-images.githubusercontent.com/39467613/72924408-a3422600-3d2f-11ea-80e8-8740d6481d06.png)

11. After the assignment, the new datetime of `activity.localTimestamp` will have the new User's Timezone
![image](https://user-images.githubusercontent.com/39467613/72924429-ac32f780-3d2f-11ea-8d38-64f1c19ac8d4.png)

Thanks :relaxed:

**Comment by tommyJimmy87** [comment]
Hi @VictorGrycuk ! Thanks for the fast answer first of all! 

I don't know if I understood very well the steps, but I'll try to explain myself better with all the steps we did to reproduce the issue: 

1. First assumption is that we have the Virtual Assistant deployed locally.

2. Second assumption is that we want to perform the test with 2 different laptops, where the first laptop is the client (for us is Teams) and the second laptop is the server where we are running the VA.

3. Third assumption is that we have 2 different Timezone set up on the 2 laptops, let's say the first one (client) will have `GMT+0300` and the server will have `GMT+0100`.

4. Then after we have everything set up we try from the client to send a request to the VA through Teams.

5. As soon as we get the request we have as parameter in the body the right timezone from the user :

![Screen Shot 2020-01-23 at 14 30 02](https://user-images.githubusercontent.com/21197220/72988621-e3b3a980-3dec-11ea-99a1-a7a2a56fa64f.png)

![Screen Shot 2020-01-23 at 14 29 49](https://user-images.githubusercontent.com/21197220/72988622-e3b3a980-3dec-11ea-8dea-a7bb3541b82a.png)

6. Inside the parse request we get the right Client Timezone :

<img width="1124" alt="Screen Shot 2020-01-23 at 14 34 12" src="https://user-images.githubusercontent.com/21197220/72988900-7eac8380-3ded-11ea-951c-1ed3f026dff2.png">

7. But then after the assignment of the variable (basically the new Date(activity.localTimestamp) ), we have the server Timezone: 

<img width="948" alt="Screen Shot 2020-01-23 at 14 36 52" src="https://user-images.githubusercontent.com/21197220/72989069-d77c1c00-3ded-11ea-871e-9dd61d671850.png">

**Comment by Batta32** [comment]
Hey @tommyJimmy87! Thanks for the detailed steps! We will be reviewing this scenario and we will back to you later 😊.

**Comment by VictorGrycuk** [comment]
Hi @tommyJimmy87!

We reached the conclusion that this is due to a limitation on how JavaScript handles the `Date` object.

However, we want to let you know that we **opened** the [issue #1612](https://github.com/microsoft/botbuilder-js/issues/1612) about this issue on the BotBuilder-JS repository. You may track the progress of this issue there, so check there as well.

As for the problem we found, when converting any date to `Date` object, JS converts it to UTC which essentially strips the original time zone. The only time zone that JavaScript can handle is the time zone of the system running JS.
You can check the [Date documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) for information.

We will let you know any progress :relaxed:
