### ISSUE TITLE
Teams Locale OnBoarding is not sent

### ISSUE THREAD

**Issue by tommyJimmy87** [microsoft/botframework-solutions#2920]
#### What project is affected?

Both Skill and VA, but mostly VA

#### What language is this in?

Typescript

#### What happens?

I'm using Microsoft Teams as channel, when at first I deploy the manifest in Teams it will run the onBoarding. Unfortunately the first time that Teams calls the Bot it doesn't include the locale (I have for example German as locale on Teams). That means that the `onboarding` or `greetings
` will be run everytime with the default locale (English in my case).

#### What are the steps to reproduce this issue?

1. Deploy the VA locally 
2. Run Ngrok and connect the url to the channel setting in Azure
3. Run in debug mode your VA
4. Install the application manifest in Teams with the same applicationId of your ChatBot
5. In the request there's no locale and so in the context obviously 
<img width="1073" alt="Screen Shot 2020-01-27 at 12 51 50" src="https://user-images.githubusercontent.com/21197220/73172764-0f43d600-4104-11ea-9f82-3bed4fd98f48.png">
6. When you do a second interaction with the ChatBot the locale is in the request
<img width="599" alt="Screen Shot 2020-01-27 at 12 57 34" src="https://user-images.githubusercontent.com/21197220/73173121-e96b0100-4104-11ea-8f2f-85f21ebe389d.png">

#### What were you expecting to happen?

To get the locale the first time I install the Teams app, if this is not possible because of limitation on Teams side (which is the case), manage the OnBoarding differently for Teams channels

**Comment by Batta32** [comment]
Hi @tommyJimmy87! Thanks for reporting the issue!

We will be replicating the scenario and back to you later 😊.

**Comment by LCarbonellRod** [comment]
@tommyJimmy87 - we successfully reproduced the issue in Typescript and C# as well, using the Microsoft Teams and Emulator as channels.

We will check where it's generated the first locale of the activity and get back to you later.

_C#_

![image](https://user-images.githubusercontent.com/37625424/73385269-a8612100-42ab-11ea-91bb-f6ca784c557b.png)


_TypeScript_

![image](https://user-images.githubusercontent.com/37625424/73385280-ac8d3e80-42ab-11ea-8c07-85e1f1d753df.png)

**Comment by VictorGrycuk** [comment]
Hi @tommyJimmy87,

We looked further into this issue, realizing this is due to how each channel handles the `conversationUpdate` activity.

We tested this in the webchat, and the same behavior is present.

With Teams and the WebChat, the activity is sent without the locale which causes the _onBoarding_ to be [sent in the default language](https://github.com/microsoft/botframework-solutions/issues/2856).
In the Bot Framework Emulator it works because the `locale`  [is added to the activity](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/app/main/src/server/state/conversation.ts#L139) as a property before being sent.

This discrepancy between the Emulator and the Teams channel is [known and it's not considered a bug](https://github.com/microsoft/BotFramework-WebChat/issues/1371#issuecomment-481291534).

We found [this recommendation](https://github.com/microsoft/BotFramework-WebChat/issues/2388#issuecomment-529561057). Please take a look at it and let us know if it works for you.

**Comment by marawanshalaby** [comment]
Hey @VictorGrycuk thanks for the recommendation, but for the use case reported by the original poster (it's the same case that I have), teams is used as a channel, so we can't initiate a client-side request to the server as indicated in the [example](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/a.welcome-event) which works for web-chat but not for teams. I understand that this [may not be considered a bug for web-chat](https://github.com/microsoft/BotFramework-WebChat/issues/1371#issuecomment-481291534), because there is a workaround for it, but we can't seem to find a workaround for this in teams. 

Is there any way to get to the user's locale in teams before sending this first message? I know that this sounds a bit minute, but the first message is the first contact that a perspective user has with our bot and having his first message shown in english and then everything else in his language would be directly noticeable by any user. 

@darrenj do you have any ideas here, related to how you guys are planning to handle the https://github.com/microsoft/botframework-solutions/issues/2856 issue?

**Comment by VidhyaSanjeevi** [comment]
@VictorGrycuk the link given in workaround for the sample in GitHub is not found, can you share any sample.

[recommended work around](https://github.com/microsoft/BotFramework-WebChat/issues/2388#issuecomment-529561057)
[suggested link in above work around not found](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event)

**Comment by Batta32** [comment]
Hi @SSanjeevi, the new link to the sample is [04.api/a.welcome-event](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/a.welcome-event).

The BF-WebChat team has reorganized the samples in the PR microsoft/BotFramework-WebChat#2762. Also, the old link is [15.d.backchannel-send-welcome-event](https://github.com/microsoft/BotFramework-WebChat/tree/9923a557c7201635610143d395fabc685937b234/samples/15.d.backchannel-send-welcome-event).

Feel free to create a new issue in the repository if you have a problem 😊.
