### ISSUE TITLE
[Calendar] CancelAllDialog cause some logic error when MainDialog changed to Waterfall

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-solutions#3027]
#### What project is affected?
Calendar(and Email/Todo/Poi?)
#### What happens?
After MainDialog changed to waterfall dialog, the CancelAllDialog called in the Dialog(like CreateEventDialog) will cause the logic error.
#### What are the steps to reproduce this issue?
Throw an exception in the CreateEventDialog.
#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/44257569/74245493-0c5cfe00-4d1e-11ea-9c78-57374a7cf7cc.png)

**Comment by xieofxie** [comment]
The logic `outerDc.CancelAllDialogsAsync()` in EndComponentAsync is the root cause (also exists in Email, ToDo). A quick fix could be skip it when `outerDc.Parent.ActiveDialog.Id == nameof(MainDialog)`. But do we have better options? Like handle route in OnBegin and EoC in OnEnd instead of WaterfallSteps.
