### ISSUE TITLE
[VA] 'Get started' is no longer handled any more

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3029]
#### What project is affected?
VAs
#### What language is this in?
C#
#### What happens?
'Get started' button used to send an event 'startOnboarding' but it is no longer handled.
#### Any screenshots or additional context?
Should we 1. remove it 2. add it back 3. point to some url instead?

**Comment by pavolum** [comment]
Thanks for filing this bug @xieofxie. We think the best thing to do is remove it. I will push a PR to next with this fix today :)

**Comment by hansmbakker** [comment]
@pavolum @xieofxie can you please reopen this, put a fixed version back, or link to a sample that shows how to handle these events?

This `startOnboarding` event was a great way to show how to handle the `postBack` event from an Adaptive Card button (because you need to handle it differently than other events: they are sent as messages rather than real events)

**Comment by xieofxie** [comment]
hi @hansmbakker I created two demos here https://github.com/microsoft/botframework-solutions/tree/hualxie/demo_for_3029

1 how to start it like a trigger utterance in on route (StartOnboardingRoute).
2 how to start it like interruption (StartOnboardingInterrupt).

Hope them help.

If you need further help, please open a new issue for this feature. People may not respond to closed issues.

**Comment by hansmbakker** [comment]
hi @xieofxie,
thank you! That's very helpful! Would it be possible to find something like this in the documentation? For other people it won't be easy to find when they have to look in a special branch of the source code.

**Comment by xieofxie** [comment]
@pavolum any thoughts for this feature? Thanks
