### ISSUE TITLE
SurpressCompletion for VA Template, Hospitality Assistant, and Enterprise Assistant

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#3043]
I noticed that in our hospitality assistant, there is a completion message after every turn. This seems to be too much. Based on our learning from customer demos, we agreed that we should do dc.SurpressCompletion message on fall back messages to avoid too much repetitive speaking in our hospitality assistant, and also verify in VA Template, and enteprise assistant - if similar experience, should do it there too. 
![image](https://user-images.githubusercontent.com/25210203/74386773-b46cd880-4dab-11ea-9f94-c3277a4c5cfa.png)

**Comment by xieofxie** [comment]
Suppress after QnA and see how it works?

**Comment by xieofxie** [comment]
@ryanlengel How do we update these samples? This is fixed in https://github.com/microsoft/botframework-solutions/pull/3129

**Comment by lzc850612** [comment]
We need to update Hospitality Assistant and Enterprise Assistant both to the latest waterfall dialog approach for main dialog and then apply this change. @xieofxie do you have bandwidth to take this? It'd be good to update both these two assistants to the latest of SDK as well as solutions lib so they're ready for v1.0 release.

**Comment by xieofxie** [comment]
@lzc850612 OK, I will make a pr for this.

**Comment by xieofxie** [comment]
@lzc850612 I found one issue: should we change these assistant point to skills in botframework-skills? Since skills here will not be updated

**Comment by lzc850612** [comment]
The assistant points to skills using the configuration in appsettings. The Azure Devops builds for botframework-skills repo skills are running now and being deployed to the same endpoints that the skills in botframework-solutions used to be deployed to. So it's just a matter of connecting to those skills. Although there wouldn't be any code changes needed in PR since that'll just be endpoint configuration in appsettings.json. One small issue is the LU files needed to add skills still need to be under dispatch folder of the VA so botskills tool can work, as the feature of using LU file from a remote location doesn't work fully (specifically for the scenarios of one LU file importing/referencing another LU file)

**Comment by ryanisgrig** [comment]
@xieofxie you can diff those samples against the latest VASample. I believe the only differences now are:
Enterprise VA has proactive messaging, hr benefits faq reference (but no LU files as that is unavailable for multi-turn at this point), professional chit chat?
Hospitality VA has caring chit chat

For the Skills you can update the solution files and remove the references to the Skill projects, as they will be removed from the repository entirely. We will have to point users to these in the docs.

**Comment by xieofxie** [comment]
fixed in next
