### ISSUE TITLE
Alternative for OnEventActivityAsync() in new VA Template

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-solutions#3054]
## User Story
The recent update to the Virtual Assistant Template has changed the base class for MainDialog. As a result, the OnEventActivityAsync() method, which was available in the older version of the template, is now missing. The documentation available [here](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-proactive-notifications/4-virtual-assistant/), still pertains to the older version of the template. Due to this, using the new Template, I am unable to handle Proactive Scenarios, which was available in the older version of the template. The new template needs to be updated to be able to handle Event activities, since it is a loss of functionality provided by the older template.

## Acceptance Criteria 
- Upgrade the new VA Template to be able to handle event activities, as provided by the older VA Template.

**Comment by lauren-mills** [comment]
Hi @manish-95, you can process your events that do not need to be processed by the dialog stack in the [DefaultActivityHandler.OnEventActivityAsync()](https://github.com/microsoft/botframework-solutions/blob/929a470b2991e180dad7820c3db59f416cf583ff/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs#L76) method. 

If your event needs to be processed by the dialog stack, for example a TokenResponse event, you can handle it in the [MainDialog.RouteStepAsync()](https://github.com/microsoft/botframework-solutions/blob/929a470b2991e180dad7820c3db59f416cf583ff/samples/csharp/skill/SkillSample/Dialogs/MainDialog.cs#L228) method. 

We will take an action to update the documentation reflecting this change.

**Comment by guru98** [comment]
What about events that want to set property in skillcontext and what about events that have to be propagate to a skill? in this case the current active skill is a Dialog in the dialog stack?

**Comment by lauren-mills** [comment]
@guru98, the current active skill is always a Dialog in the stack. If you receive an event that you want to forward to the current active skill, you can add a handler for it in the DefaultActivityHandler.OnEventActivityAsync method like [this one for TokensResponse](https://github.com/microsoft/botframework-solutions/blob/929a470b2991e180dad7820c3db59f416cf583ff/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs#L83), that catches the event, then calls dialog.Run(). This will pass the event to the waiting dialog.

For scenarios when you would have used the skillContext before, the Bot Builder SDK has introduced Actions in the 4.7 Skill Protocol as a replacement. You can find details on how to implement action support [here](https://microsoft.github.io/botframework-solutions/skills/tutorials/add-action-support/csharp/1-intro/).

**Comment by guru98** [comment]
So your suggestion is call an action that set the skillcontext skill side?
What about use SkillDialogArgs.Value in the BeginDialogAsync? It'is supported? I make a first try without luck

**Comment by guru98** [comment]
Ok SkillDialogArgs works

**Comment by darrenj** [comment]
Great!

**Comment by hansmbakker** [comment]
@lauren-Mills / @darrenj can you please point to the docs that explain how to handle e.g. action events from adaptive cards in the new bot structure?

`OnEventActivityAsync` was moved from `MainDialog` to `DefaultActivityHandler` and in its new form it it is not possible to call `BeginDialogAsync` (lack of dialog context access).

You say that you can also handle it in `RouteStepAsync` but I cannot find a good example how to do that properly.

**Comment by guru98** [comment]
If you are inside a Dialog flow it doen't change you can use, for example, EventPrompt.
On the Virtual assistant in the DefaultActivityHandler you have to forward the event to the dialog waiting in the stack using await _dialog.RunAsync(turnContext, _dialogStateAccessor, cancellationToken). If you have a skill that have to send an event to the client you have to intercept it in the DefaultActivityHandler in the VA and explicitally send it to the client using SendActivityAsync

**Comment by hansmbakker** [comment]
Ok, so my question is - how to properly use the forwarded event?

Is there any documentation or a sample for that?

Use case: I have a download event that should trigger a new DownloadDialog. This DownloadDialog should perform several actions and send several messages to the user that sent the event.
Before, this was possible from the MainDialog event handling function since there was access to DialogContext which you could use for BeginDialogAsync.

**Comment by guru98** [comment]
if understand well you hav to manage it inside the main dialog in the RouteStepAsync method checking activity.Type==Event and then calling BeginDialogAsync. e.g.
case "SampleAction":
                            {
                                SampleActionInput actionData = null;

                                if (ev.Value is JObject eventValue)
                                {
                                    actionData = eventValue.ToObject<SampleActionInput>();
                                }

                                // Invoke the SampleAction dialog passing input data if available
                                return await stepContext.BeginDialogAsync(nameof(SampleAction), actionData);
                            }
You have to doublecheck that in DefaultActivityHandler you forward the event to the main dialog:
e.g. return _dialog.RunAsync(turnContext, _dialogStateAccessor, cancellationToken);

**Comment by hansmbakker** [comment]
@guru98 I tried it, and it might work for normal events but in the past, VA used `RouterDialog`. 
`RouterDialog` contained this [workaround to treat `postBack` events from Adaptive Cards as real events (instead of messages)](https://github.com/microsoft/botframework-solutions/blob/master/sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/RouterDialog.cs#L56-L60).

VA does not use RouterDialog anymore and therefore handling of `Adaptive Card Button`s is now broken. Furthermore, the [`postBack` activities they send (with activity type = `message`) contain no text so they break VA since it is being sent to LUIS instead](https://github.com/microsoft/botbuilder-dotnet/issues/1211).

This is not described in the Migration documentation. Instead, [the sample how to handle these button events is simply removed from VA](https://github.com/microsoft/botframework-solutions/issues/3054).

@darrenj @lauren-mills could you please help with this?
