### ISSUE TITLE
No manifest file is generating after event skill deployment

### ISSUE THREAD

**Issue by marutisalunkhe** [microsoft/botframework-solutions#3070]

**Comment by xieofxie** [comment]
Hi @marutisalunkhe you could add yours following this https://github.com/microsoft/botframework-solutions/pull/3081

But this skill is not maintained now since required EventBrite API is not public any more https://groups.google.com/forum/#!topic/eventbrite-api/-E0MG7THMsc
Do they change it recently? Thanks

**Comment by darrenj** [comment]
Indeed - it would appear they have deprecated the API as per [this](https://www.eventbrite.com/platform/docs/changelog). They are pointing people at a [distribution partner relationship](https://www.eventbrite.com/l/distribution-partnerships/) which might provide a way forward. I'll update the docs to highlight this and will hold off removing the skill until we know more.
