### ISSUE TITLE
[Docs] - Deprecation warning of luis packages

### ISSUE THREAD

**Issue by mschray** [microsoft/botframework-solutions#3136]
/skills/tutorials/create-skill/csharp/2-download-and-install/

After the command to install npm install -g **@microsoft/botframework-cli botdispatch luis-apis** 
there is a message that these tools are no longer maintained and there is a suggestion for another package.  What unclear is should the documentation direct you to install this new package or will the tutorial only work with this version?

#####################################################################################################
# Active development of this SDK has been moved to @azure/cognitiveservices-luis-authoring package. #
#             This package is in maintenance mode and will be deprecated in July 2019.              #
#               Visit https://aka.ms/azure-sdk-for-js-migration for more information.               #
#####################################################################################################

**Comment by lauren-mills** [comment]
Hi @mschray, we have not updated from the luis-apis npm package to the new bf:luis CLI due to some features we need that will be added in their next release. Please continue to use the listed luis-apis package from our documentation and we will update it as soon as all the features are finished. We anticipate being able to update in our next release.

**Comment by lauren-mills** [comment]
Closed by #3256. The luis-apis tool will be removed from the deployment instructions in our next release.
