### ISSUE TITLE
Newly generated Email.cs changed the member signatures

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-solutions#314]
**Project**
Email Skill and LuisGen

**Description**
Newly generated Email.cs changed the member signatures

**To Reproduce**
Use luisgen to generate *cs file from the email.luis in email skill sample project

**Expected behavior**
The EmailSkillTest project still builds, and all UTs pass

**Actual behavior**
The test project does not build any more.
This is the only difference between the original(left side) and the newly generated(right side) email.cs from luisgen.
![sig change](https://user-images.githubusercontent.com/44714043/48641490-cedcba00-e98e-11e8-9c74-044bf1f43596.jpg)

I then attempted to change the signature to new from override to accommodate the generated changes mentioned above, however it seems obviously not that simple as it started failing UTs and behaves weird. 
![ut](https://user-images.githubusercontent.com/44714043/48641537-efa50f80-e98e-11e8-992a-61f20f88a6af.jpg)

**Additional context**
 I’m using luisgen v2.0.2 and later.

**Comment by lzc850612** [comment]
Currently in order to support testing we need to be able to have Mock intents and the 'virtual' functions are to support this. Right now LuisGen doesn't support generating the model class with virtual methods so we have to do this manually. I'm adding a document that contains instructions on how to do this so people won't be blocked.
