### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by savipanch** [microsoft/botframework-solutions#3236]
/skills/tutorials/create-skill/typescript/4-provision-your-azure-resources/

I tried to set up the virtual assistant in TypeScript by by following these instructions however the deployment script may have some deprecated commands - 
While running ./deployment/scripts/deploy.ps1 I first got 
```This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.```

Then I modified the deploy.ps1 script and replaced ```group deployment``` with ```deployment group``` and then encountered the following error in deploy_log.txt

```ERROR: az deployment operation sub: 'group' is not in the 'az deployment operation sub' command group. See 'az deployment operation sub --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview```

I was using the latest package for Azure CLI. It looks like the script may have commands from an older Azure CLI. Could you please fix this?

**Comment by Batta32** [comment]
Hi @savipanch! Thanks for reporting the issue.

It's just a **deprecation warning** from `az` that should not block the deployment execution.

Currently, we are updating the TypeScript solutions that contains the solution to that deprecation warning. It will be available once these changes are implemented and published.

We will keep you updated 😊!

**Comment by savipanch** [comment]
Yes, that made sense to us too that being deprecated should not stop the deployment but it error-ed out. 
```{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': 'The template deployment failed because of policy violation. Please see details for more information.', 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models_py3.ErrorResponse object at 0x10cd5b820>], 'additional_info': None}```
```! Deployment failed. Please refer to the log file for more information.```

The log file had this message about the deprecated commands.

**Comment by Batta32** [comment]
Hi @savipanch, we are closing this issue as it will be fixed in the next release of TypeScript. Please, feel free to reopen it if you are still having the problem😊.

Before they are published you can use the packages published in MyGet as daily builds:
- [generator-botbuilder-assistant@1.0.9-preview171](https://botbuilder.myget.org/feed/aitemplates/package/npm/generator-botbuilder-assistant/1.0.9-preview171)
- [botbuilder-solutions@4.5.0-preview223](https://botbuilder.myget.org/feed/aitemplates/package/npm/botbuilder-solutions/4.5.0-preview223)

To use the `generator-botbuilder-assistant`, you should uninstall it if you already have one and then install the one of MyGet:
```bash
npm uninstall -g generator-botbuilder-assistant
```

```bash
npm install -g generator-botbuilder-assistant@1.0.9-preview171 --registry https://botbuilder.myget.org/F/aitemplates/npm
```

To integrate `botbuilder-solutions` daily build you have two different options, we recommend the first option as it's the easiest one (take into account to remove the `package-lock` and `node_modules` of your bots):
- Option 1: Add a `.npmrc` file pointing to the registry `https://botbuilder.myget.org/F/aitemplates/npm`, and updating the `package.json` to point the `botbuilder-solutions` version to `4.5.0-preview223`
- Option 2: Download the tgz of `botbuilder-solutions` referencing it directly in the package.json with an absolute path
```bash
npm pack botbuilder-solutions@4.5.0-preview223 --registry https://botbuilder.myget.org/F/aitemplates/npm
```
