### ISSUE TITLE
Duplicate utterances in LUIS models

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#327]
**Project**
Virtual Assistant, Skills

**Description**
The dispatch tool reports several duplicate utterances among the skills and the general models, would it be possible to clean them up?

**To Reproduce**
run dispatch refresh --bot YourBotFile.bot on a deployed assistant and inspect the summary.html file.
Here is a partial screenshot:
![image](https://user-images.githubusercontent.com/12264946/48775995-a01b5800-ec9c-11e8-9b47-dc3cd54450d5.png)

**Expected behavior**
I would expect 0 duplicates among the deployed models.

**Comment by lauren-mills** [comment]
This is because we are using the prebuilt domain models and they have overlap. We raised this with the prebuilt model team and they are working on a Utility model to resolve this.

**Comment by gabog** [comment]
The problem here is  that it seems that hi and some other General intents have been put in the none of the skills (see hi in LUIS email) and now dispatcher can not recognize a simple hi and the latest build is not working as expected.
@darrenj, can we get this fixed asap? The assistant doesn't seem to work as it is right now.
Thanks

**Comment by lzc850612** [comment]
@darrenj has sent out the latest language models. We'll try to get the models into our code base ASAP. Please bear in mind that this is actually quite some work because we'll have to incorporate the new models manually and making sure the recent manual changes to the .lu files are integrated correctly. 

Ideally in the long-term, we shouldn't be making changes to the .lu files manually, and every time there's requirement for new utterances/intents, we should ask the pre-built domain team for an update. We also need to put the E2E test in place so that when we make new changes we'll run the E2E test as part of the validation and if it fails the PR cannot be merged to make sure the change is not breaking existing features.

**Comment by gabog** [comment]
Thanks!, I am working with some models that I manually cleaned up in the meatime.

**Comment by DingmaomaoBJTU** [comment]
@gabog Hi, I just tried the latest dispatcher code under VA in master branch, and "hi" can be recognized as General intent. (Here is how I do this: run Virtual-Assistant\src\csharp\assistant\DeploymentScripts\update_all_deployment_scripts.bat and get the dispatch.luis under \en)
Did you generate the dispatcher by yourself or use the dispatcher under VA project? If you generate the dispatcher by yourself, **please not include the None intent for each skill luis.** You can take "Virtual-Assistant\src\csharp\assistant\CognitiveModels\LUIS\en\dispatch.lu" as an example.

**Comment by gabog** [comment]
I had to regenerate the dispatcher because calendar is broken, how do you exclude the none intent on regeneration?

Sent from mobile

________________________________
