### ISSUE TITLE
Problem when deploying virtual assistant - JavaScript/TypeScript

### ISSUE THREAD

**Issue by igor17400** [microsoft/botframework-solutions#3272]
#### What project is affected?
I have followed this tutorial https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/typescript/4-provision-you-azure-resources/ and when I tried to execute the './Deployment/Scripts/deploy.ps1' file, it did not work due to some errors.

#### What language is this in?
JavaScript/TypeScript

#### What happens?

<img width="1062" alt="Screen Shot 2020-04-07 at 15 44 53" src="https://user-images.githubusercontent.com/42355184/78707247-bacc8c00-78e6-11ea-9552-67fede94e311.png">

#### What are the steps to reproduce this issue?
Just follow the tutorial link above and the error will happen. No code change is needed. 
1) yo botbuilder-assistant
2) az login
3)  ./deployment/Scripts/deploy.ps1

#### What were you expecting to happen?
To successfully deploy the chatbot on Azure

#### Any screenshots or additional context?
I'm running this code on a Mac OS Catalina 10.15.3

**Comment by Batta32** [comment]
Hi @igor17400, thanks for reporting this issue!

We will be reviewing it and we will back to you later 😊

**Comment by Batta32** [comment]
Hi @igor17400, sorry for the delay. We successfully **reproduced** the issue using the steps you mentioned, we will be validating some workarounds and we will back to you later 😊.

![image](https://user-images.githubusercontent.com/11904023/79131249-abce5980-7d7e-11ea-87cd-f948e2869208.png)

**Comment by Batta32** [comment]
@igor17400, this issue **will be fixed** in the next version of the [generator-botbuilder-assistant](https://www.npmjs.com/package/generator-botbuilder-assistant) in npmjs.

We identified some **workarounds** that will work for you:
1. Use the [sample-assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/typescript/samples/sample-assistant) instead of the one created by the generator.
1. If you want to use the created by the generator, update this [line](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-assistant/deployment/resources/template.json#L309) in the `template.json` of your generated Virtual Assistant to this:
```
"serverFarmId": "[concat('/subscriptions/', Subscription().SubscriptionId,'/resourcegroups/', resourceGroup().name, '/providers/Microsoft.Web/serverfarms/', parameters('appServicePlanName'))]",
```

Please check the issue #2762, specifically this [comment](https://github.com/microsoft/botframework-solutions/issues/2762#issuecomment-562240133).

Let me know if it resolves your issue 😊.

**Comment by Batta32** [comment]
Hi @igor17400, we are closing this issue as it will be fixed in the next release of TypeScript. Please, feel free to reopen it if you are still having the problem 😊.

Before they are published you can use the packages published in MyGet as daily builds:
- [generator-botbuilder-assistant@1.0.9-preview171](https://botbuilder.myget.org/feed/aitemplates/package/npm/generator-botbuilder-assistant/1.0.9-preview171)
- [botbuilder-solutions@4.5.0-preview223](https://botbuilder.myget.org/feed/aitemplates/package/npm/botbuilder-solutions/4.5.0-preview223)

To use the `generator-botbuilder-assistant`, you should uninstall it if you already have one and then install the one of MyGet:
```bash
npm uninstall -g generator-botbuilder-assistant
```

```bash
npm install -g generator-botbuilder-assistant@1.0.9-preview171 --registry https://botbuilder.myget.org/F/aitemplates/npm
```

To integrate `botbuilder-solutions` daily build you have two different options, we recommend the first option as it's the easiest one (take into account to remove the `package-lock` and `node_modules` of your bots):
- Option 1: Add a `.npmrc` file pointing to the registry `https://botbuilder.myget.org/F/aitemplates/npm`, and updating the `package.json` to point the `botbuilder-solutions` version to `4.5.0-preview223`
- Option 2: Download the tgz of `botbuilder-solutions` referencing it directly in the package.json with an absolute path
```bash
npm pack botbuilder-solutions@4.5.0-preview223 --registry https://botbuilder.myget.org/F/aitemplates/npm
```
