### ISSUE TITLE
how to pass data from virtual assistant to a skill and vice versa

### ISSUE THREAD

**Issue by vannela** [microsoft/botframework-solutions#3282]
I am trying to pass **data** from VA to a Skill like below in RouteStepAsync event in MainDialog of VA:

var dispatchIntentSkill = dispatchIntent.ToString();
var skillDialogArgs = new SkillDialogArgs { SkillId = dispatchIntentSkill, **Text = userProfile.CorpId** };
// Start the skill dialog.
return await stepContext.BeginDialogAsync(dispatchIntentSkill, **skillDialogArgs**);

How do I read the data that is passed to Skill in Skill project?

**Comment by sidmore** [comment]
@vannela 

Can you kindly identify what version of VA and Skill are you using?In my setup I am using version:0.8. 

The right way to pass data back and forth between VA and Skill is to set the Value property instead of the Text property.

a. Send Data from VA to Skill Setup:-
1. VA 
ClassName: MainDialog.cs
Set Value property of SkillDialogArgs to "Hello"
![VADispatchIntent](https://user-images.githubusercontent.com/29606792/79256807-7e94b080-7e3d-11ea-8892-42878b96da6e.PNG)

2. Skill
ClassName: DefaultActivityHandler.cs 
![SkillDefaultActivityHandler](https://user-images.githubusercontent.com/29606792/79257136-0b3f6e80-7e3e-11ea-85fd-c687559607b8.png)

b. Send Data from Skill To VA Setup:-
1. Skill
ClassName: DefaultActivityHandler.cs
Set Value property of reply to "World"
![SkillToVa](https://user-images.githubusercontent.com/29606792/79257889-265eae00-7e3f-11ea-9daf-9c543af79baf.PNG)

2. VA
ClassName: SkillController.cs
![SkillController](https://user-images.githubusercontent.com/29606792/79257961-455d4000-7e3f-11ea-91fd-7f827ef2b604.PNG)

This is how I was able to pass Data back and forth between VA and Skill. Please let me know if you still have any issues.

**Comment by darrenj** [comment]
Pending item to go in the docs but some more detail [here](https://github.com/microsoft/botframework-solutions/issues/2456#issuecomment-602568038) which might be useful

**Comment by peterinnesmsft** [comment]
@darrenj based on our previous offline conversation, assigning this to you to add docs - consider this your tracking issue! :)

**Comment by peterinnesmsft** [comment]
Actually, let's use #2456 since it's also basically tracking an ask to update the docs for the same information, and that was the original, so this is essentially a dupe.

**Comment by Vijay2704** [comment]
Hi,
i tried passing data from VA to skill, it is working but 
**b. Send Data from Skill To VA Setup:- it is not working.**
i got **_handler** error
