### ISSUE TITLE
AdaptiveCards 1.2.3. Throws NRE under certain concurrency situations.

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botframework-solutions#3302]
#### What project is affected?
Microsoft.Bot.Solutions

#### What language is this in?
C#

#### What happens?
AdaptiveCards 1.2.3 seems to have a threading issue in the calls to Newtonsoft. Calls to FromJson if executed concurrently can occasionally throw a NRE.
1.2.4 is out and appears to fix the issue assume this will get updated on next release.

#### What are the steps to reproduce this issue?
Currently only getting this in Unit tests and only sporadically so very hard to give a diffenitive set of steps.

**Comment by peterinnesmsft** [comment]
Good morning @DavidStrickland0,

As you point out, this is a concurrency-related issue in the implementation of the Adaptive Cards SDK, which has since been addressed in 1.2.4. Corresponding fix is located in GitHub: https://github.com/microsoft/AdaptiveCards/pull/3548.

As a mitigation, I think you have probably identified the quickest path forward which is to use a later version of the SDK. In the interim, I will follow up with the team to see if there is any objection to us updating to use a later version of the SDK in the Microsoft.Bot.Solutions library.

Let me know if you run into any other issues in the meantime relating to this particular issue.

**Comment by peterinnesmsft** [comment]
Updated the package version to 1.2.4, so this should address running into the concurrency issue.
