### ISSUE TITLE
command group 'group deployment' is deprecated

### ISSUE THREAD

**Issue by Jay-study-nildana** [microsoft/botframework-solutions#3309]
'This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.'

I am getting this warning when I tried to use the virtual assistant template. I have a PR with a fix, but as per guidelines, I am create a issue first.

**Comment by taicchoumsft** [comment]
Thanks for submitting a fix for this Jay-study-nildana! The team will review this and get back to you.

**Comment by peterinnesmsft** [comment]
Hi @Jay-study-nildana,

Thanks for reaching out about this and for the proactive PR to address! As we are currently working towards a GA release for Virtual Assistant within the next few weeks, we have actually already made a fix for this in our 'next' branch, which represents the upcoming changes we are tailoring for this particular release. We anticipate this particular issue will otherwise be handled within 'master' when we merge this change.

Having discussed as a team, given that there is no particular urgency for this issue and we intend to otherwise merge next into master soon, we will opt to fix this particular issue through that path instead.

We value the time you took to proactively address this, so thank you very much! We welcome any other contributions that you may have!
