### ISSUE TITLE
Does Azure Bot service support Managed Identities and App Service Environment?

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3328]
Does Azure Bot service support Managed Identities and App Service Environment?

**Comment by ryanisgrig** [comment]
Hi @gagankohli2000,

The issue tracker is not for questions. Please ask questions on https://stackoverflow.com/questions/tagged/botframework. Thank you!

**Comment by peterinnesmsft** [comment]
Hi @gagankohli2000,

A Virtual Assistant or Skill is otherwise just a web application, so when deployed to Azure is subject to the same standards as other web applications with regards to support for Managed Identities. Out of the box, our deployment scripts deploy as a regular App Service resource. I don't have any reason to believe that it shouldn't work on App Service Environment, but to do so would require adjustments to the out-of-box content that we provide - in particular, I suspect our ARM template and deployment scripts.

Hopefully this helps answer your question, so I will resolve this issue. If it does not answer your question, then feel free to reactivate and clarify, and we will do our best to assist.

Have a great day!
