### ISSUE TITLE
Skill stops sending proactive notifications once it sends endofconversation to VA

### ISSUE THREAD

**Issue by nebhagat** [microsoft/botframework-solutions#3330]
#### What project is affected?
Skill sending proactive notifications

#### What language is this in?
C#

#### What happens?
Once flow is terminated with skill and it sends endofconversation activity to VA, proactive notifications no more work.

#### What are the steps to reproduce this issue?
Add a skill which sends proactive notifications to the VA.
Switch context to this skill via VA and complete the flow.
(endofconversation activity deletes the mapping from skillConversationIdFactory)
Trigger skill API which sends proactive notifications.
notification does not get posted.

#### What were you expecting to happen?
notifications should work post closing the flow with skill via VA.

If the skillbot does not send `endofconversation` once it's done setting up notification, notifications keep working even when skills are switched.

Is it fine to end the flow via VA (using `start over` etc) than expecting a skill to close the conversation?

**Comment by darrenj** [comment]
Can’t you share a little more information on how you are generating the proactive notifications? It seems from a Skill?

As you say - once a Skill has finished and sends end of conversation that logical conversation is over. In your scenario you wish the Skill itself to resume conversation via the skill protocol?

To date the proactive work we have done has focused on having an external entity (e.g. event hub) identify something of note for a user and push an event back to the main bot (VA) which can resume the conversation with the end user and send on to the user - as per:

https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-proactive-notifications/1-intro/

Would this scenario work for you? I.e. the only durable conversation to my mind is between the user+VA rather than the Skill. Happy to consider additional models if this doesn’t work for you?

**Comment by okulygin** [comment]
@darrenj regarding the proactive notifications - we have scenario when we need a skill to handle incoming event from event hub and send proactive messages to subscribed users. These events are skill-specific, and VA has no knowledge on how to render messages for them. 
Is it possible for a skill to send a proactive notification through a VA? 

[**EventHub**] --_Event_--> [**Skill**] --_Activity_--> [**VA**] --_Activity_--> [**Teams**]

After posting initial activity skill would also need conversationId, so in future it can update existing conversation when an "Update" event arrives...

**Comment by darrenj** [comment]
Morning,

Agreed, we've been discussing internally and recognise we can likely better provide more control/configuration to enable this implementing your own `SkillConversationIdFactory` does provide you control over this.

In the example below you can see I'm just omitting the call to the [base implementation](https://github.com/microsoft/botbuilder-dotnet/blob/c42dcde28bae9d12cffb666b6323b0830bd3122f/FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/SkillConversationIdFactory.cs#L39) which will remove the record.

You will need something to tidy these up and my suggestion typically is to explore [CosmosDB TTL](https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live) to perform this quite elegantly.

```csharp
 public class CustomSkillConversationIdFactory : SkillConversationIdFactory
    {
        public CustomSkillConversationIdFactory(IStorage storage) : base (storage)
        {

        }

        public override Task DeleteConversationReferenceAsync(string skillConversationId, CancellationToken cancellationToken)
        {
            // Rely on external process to cleanup old ConversationIds. Likely TTL configuration on per-record basis within CosmosDb

            //return base.DeleteConversationReferenceAsync(skillConversationId, cancellationToken);
            return Task.CompletedTask;
        }
    }
```

I think this addresses your need - could you give it a try and let us know? Feel free to re-open if you need any more help. I'll then get some documentation added to cover this scenario in a little more detail.
