### ISSUE TITLE
Not able to add QnA maker to a Skill

### ISSUE THREAD

**Issue by badhonkundu** [microsoft/botframework-solutions#3433]
#### What project is affected?
Bot Framework Skill

#### What language is this in?
C#

#### What happens?
When adding a QnA maker to a Skill using update_cognitive_model.ps1, it errors out.

#### What are the steps to reproduce this issue?
Just like we would add new qna makers/knowledge bases in a Virtual Assistant I follow the below steps for adding it to a Skill:

1. Create a Skill using the latest Skills template(C# - 4.9.1)
2. Deploy the skill to Azure using deploy.ps1 that you can find in the solution's "/Deployement/Scripts/" folder
3. Update the cognitivemodels.json with the required details of the qna maker - add the details in the "knowledgebases" - format given below:

"knowledgebases": [ { "id": "hr", "subscriptionKey": "", "hostname": "https://.azurewebsites.net/qnamaker", "kbId": "kbId", "name": "", "endpointKey": "" } ]

4. Run the update_cognitive_models.ps1 in the same folder as above.

5. When I run the above script, I get an error- given below: 
![AddQnAMakerToSkillError](https://user-images.githubusercontent.com/63103301/83337562-2ecd5400-a2da-11ea-9826-9d8a6cf9782e.png)

Please note that I have tested adding the same QnA to a Virtual Assistant and it works fine. I have double checked the values for each of the keys provided and they are correct.

#### What were you expecting to happen?
QnA maker gets added to the skill

#### Can you share any logs, error output, etc.?
Error in logs (update_cognitive_models_log.txt): AZ CLI passes minimum version. Current version is 2.6.0 Sorry unable to open [C:\Users\jyotikub\source\repos\MyAssistant1\TestHRSkill\TestHRSkill\Deployment\Scripts..\Resources\QnA\en-us\hr.json]

**Comment by darrenj** [comment]
I think it's trying to write to that directory (Resources\QnA) which doesn't exist as the KB wasn't created through the normal deployment scripts. Whilst we could update the update script to ensure this directory is created adding QnA to Skills is not something likely to work well as the training data used for Skill registration cannot be surfaced through the manifest file?

i.e. when you register a Skill it needs examples of utterances (normally through LU files) referenced in the manifest to train the local dispatcher so it can then know when to pass QnA requests across.

We typically recommend that you register additional QnAMaker KBs at the VA level rather than skills because of this. Would that work for you?
