### ISSUE TITLE
Botconnect skills command isn't updating VA's Luis app 

### ISSUE THREAD

**Issue by DishaAgarwal** [microsoft/botframework-solutions#3487]
#### 
<img width="785" alt="Botconnect" src="https://user-images.githubusercontent.com/11506427/85673103-2c93c500-b6e1-11ea-8c79-483fa375ec09.png">

After connecting the botskills command, I don't see any changes to my Luis dispatch app.

**Comment by Batta32** [comment]
Thanks @DishaAgarwal for reporting this issue. We will be reviewing this and we will back to you ASAP!

**Comment by Batta32** [comment]
Hi @DishaAgarwal - sorry for the delay. 

To resolve the issue you have to follow these **steps**:
1. **Install** the needed .NET Core runtime version ([2.1.0](https://dotnet.microsoft.com/download/dotnet-core/2.1#runtime-2.1.0)).
1. **Run** the botskills connect command and see the results.

The problem happens because, as the attached image points, you have the .NET Core runtime `3.1.5` version and Dispatch **needs** .NET Core runtime `2.1.0` or higher but less than `3.0.0`.

![image](https://user-images.githubusercontent.com/11904023/86162268-ea092880-bae4-11ea-9186-73db7abe4157.png)

Last but not least, you can check your .NetCore runtimes excecuting `dotnet --list-runtimes`

**Comment by DishaAgarwal** [comment]
Hi, 

Thanks! It worked after changing the version.

**Comment by Batta32** [comment]
Awesome! I'll close this issue.

**Comment by DishaAgarwal** [comment]
Hi @Batta32 , Just wanted to confirm when support for .NET Core Version 3.1.5 be available for botconnect command?

**Comment by Batta32** [comment]
Hi @DishaAgarwal, botskills internally executes [botdispatch](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Dispatch) which is the tool that **needs** `.NET Core` 2.1.0. or higher but less than 3.0.0.

It is planned to migrate botdispatch to [botframework-cli](https://github.com/microsoft/botframework-cli#available-commands), so we expect that botdispatch **continue using** the same supported .NET Core versions until the tool is migrated to botframework-cli.

![image](https://user-images.githubusercontent.com/11904023/86248877-df05d500-bb84-11ea-992b-496ac8a09efc.png)

**Comment by DishaAgarwal** [comment]
@Batta32, Thanks for the update!
