### ISSUE TITLE
Remove confirmation dialog for cancel command

### ISSUE THREAD

**Issue by feich-ms** [microsoft/botframework-solutions#351]
**Project**
Skills

**Description**
When users say 'Cancel', confirmation dailog should not be prompted to let users comfirm.

**To Reproduce**
Say 'Cancel' in any inprogress dialog.

**Expected behavior**
No confirmation dialog is prompted and cancel the dialog directly.

**Screenshots**

**Additional context**

**Comment by darrenj** [comment]
@feich-ms Can you share more background as to why you think the confirm prompt should not be used?

**Comment by feich-ms** [comment]
@darrenj This feedback comes from BMW team. Per their suggestions, 'Cancel' will cancel the flow directly and confirmation is not that needed. @gabog can confirm.

**Comment by gabog** [comment]
Right, this came up in a couple of PoCs. The cancel confirmation becomes annoying, especially if the bot misunderstood your intent. 
In general, the cancel confirmation gets in the way and is kind of robotic (unless the user is about to lose valuable data). Not sure if you got feedback from other sources. Can we at least make it a config setting If you don't want to remove it?

**Comment by darrenj** [comment]
Hopefully the misunderstood behaviour is greatly improved since the introduction of a confidence measure before triggering that intent. I've accepted the change but I'm concerned about the situation where we cancel incorrectly and loose a users state/progress - this should be rare now but that's where the cancel prompt comes in of value. Perhaps this is where the propsoed consult changes to the dialog stack can be used to enable cancel to "consult" a dialog on whether it has outstanding "writes" and if so prompt to make sure. 

I'll move this to Vanadium to track the consult change

**Comment by lauren-mills** [comment]
Done.
