### ISSUE TITLE
Migration of data from from Older version of VA\Skills to latest version 1.0 of VA\Skills

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botframework-solutions#3605]
#### What project is affected?
VA and Skills
#### What language is this in?
C#
#### What happens?
We have a live VA and skills deployed and being used in Prod. This uses older version of VA and Skills from BF v 0.3. This is where the skills are loaded in memory rather than a separate process.

Now we are planning to move to latest version of VA\Skills that is 1.0. We need guidance on how to migrate the data regarding conversations and from old version cosmos db to new cosmos db.

The approach we tried so far:
1. Install Old VA\Skills
2. Create some conversation data (teams channel)
3. Install new VA\skills
4. Migrate the conversation data from old cosmos to new cosmos
5. Point the old VA to Url of new VA
6. Tried continue conversation: fails due to 401 unauthorized.
7. Tried change local new VA username\password in appsettings.json to old VA username\pw
8. Failure happens at BF code Failed to acquire token for client credentials. (AADSTS7000215: Invalid client secret is provided. at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.<GetTokenAsync>
9. Tried creating a identity for old VA and assigned it as a contributor in new VA cosmos db. still get error at step 8.

#### What are the steps to reproduce this issue?
See above.

I looked into the botbuilder source code https://github.com/microsoft/botbuilder-dotnet/blob/e5d5fa0c9e067a56557b9fabd85943d94d1c9819/libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs. Not very useful

Stack trace (for failure at step 8)
at Microsoft.Bot.Connector.Authentication.Retry.<Run>d__0`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.<GetTokenAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.<Microsoft-Bot-Connector-Authentication-IAuthenticator-GetTokenAsync>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.Authentication.AppCredentials.<GetTokenAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.Authentication.AppCredentials.<ProcessHttpRequestAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Bot.Builder.BotFrameworkAdapter.<SendActivitiesAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass25_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

#### What were you expecting to happen?

We are looking for clear steps of how to preserve the data when we move from old cosmos db to the new cosmos db. After that how the new VA can replace seamlessly the old VA.

#### Can you share any logs, error output, etc.?
Shared above

**Comment by ipraveenMS** [comment]
Alternatively we are also ok with steps with patch the older version of VA\skills with newer code.

Any help? Its been 7 days without response.

**Comment by peterinnesmsft** [comment]
Sorry for the delay @ipraveenMS, we will take a look at this. @lauren-mills could you take an initial pass at this?

**Comment by lauren-mills** [comment]
@ipraveenMS - can you explain what you did for steps 4 and 5 in more detail? Did you copy the records directly from the old cosmos into the new one or did you try to modify the schema at all? Also, when you say you pointed the old VA to the url of the new VA what/where did you set this?

**Comment by ipraveenMS** [comment]
4. Migrate the conversation data from old cosmos to new cosmos:
I used a azure db migration tool to copy the data from old cosmos db to new cosmos db. I have the code changes to handle schema changes in the de-serialization code in new code.
5. Point the old VA to Url of new VA:
The bot is a teams bot when the old VA deployed to teams. I changed its (team bots) url to point to the new VA.

I am not saying here what I did is the defacto way, I am at the moment looking for a way that works. Our aim is to update the running production code of old bot to the new code base. But I do not see a documented way to do that.

**Comment by lauren-mills** [comment]
Thanks for this context, it helps. I'm looking into to see if I can figure out the authentication issue.

**Comment by lauren-mills** [comment]
In the Teams manifest, under the bots tab, did you only change the messaging endpoint, or did you click edit at the top and select your new VA from your existing bots?

![image](https://user-images.githubusercontent.com/27976702/90669264-3419ab00-e206-11ea-9a0f-5b7577e58a7d.png)

**Comment by ipraveenMS** [comment]
We have tried both. And both do not work.
Approach 1: Switch URL and bot:
When I tried this the bot completely stopped responding to the channel. (updated version number, reinstalled to channel, tried many times, tried different channels and other debugging)
Also even if that works, this runs into a practical issue which we foresee now itself. That is, teams team need a one-two week approval process for any new bots to included in their store. In this instance its a new bot since we installed a new app instance. (This is where we need the proper upgrade story from your team) We cannot afford to have a weeks of downtime.
Approach 2: Switch only Url:
This is what I explained above and it does not work also with errors in my original (top of the page) error report.

**Comment by peterinnesmsft** [comment]
Hi @ipraveenMS, thanks for additional response. @lauren-mills will pick this back up next week on Monday - apologies for the delays.

**Comment by lauren-mills** [comment]
Ok, this is all helpful, thank you.

It sounds like the best path forward is to start updating your projects instead of replacing them with new ones. There are a number of steps you will need to take. Here is a summary, and I can go into more detail on each step as needed:

### Update your skill projects.
If you are using our prebuilt skills, I recommend you start with the latest projects from microsoft/botframework-skills and redeploy them. This will save you a lot of manual migration work. For custom skills, due to how many things have changed between v0.3-beta and 1.0, I recommend starting with the latest [skill template](https://marketplace.visualstudio.com/items?itemName=BotBuilder.VirtualAssistantTemplate), then migrating your existing dialogs and responses into that new project. Then the main things you will need to change are:
1. Register your custom dialogs in [Startup.cs](https://github.com/microsoft/botframework-solutions/blob/b5a7a0c8a9b8d8579b7d34077d645d339fc55845/samples/csharp/skill/SkillSample/Startup.cs#L120)
1. Update the routing logic in [MainDialog.cs](https://github.com/microsoft/botframework-solutions/blob/b5a7a0c8a9b8d8579b7d34077d645d339fc55845/samples/csharp/skill/SkillSample/Dialogs/MainDialog.cs#L199) to route to your dialogs appropriately
1. Update your responses to use [LG](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-language-generation?view=azure-bot-service-4.0&tabs=csharp) instead of the 0.3-beta JSON files.
1. Deploy the skills to separate endpoints (you can reuse the existing resources from your VA deployment, but you will need a separate app service per skill)
1. Update your [appsettings.json](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/skill/SkillSample/appsettings.json) file to point to your existing Azure resources
1. Update the [cognitivemodels.json](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/skill/SkillSample/cognitivemodels.json) file to point to your existing skill LUIS models
1. Update the [wwwroot/manifest/manifest-1.1.json](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/skill/SkillSample/wwwroot/manifest/manifest-1.1.json) file with your skill

### Update your Virtual Assistant project.
Similar to the skills, I think it will be simpler for you to start from the latest template and copy any additional logic or dialogs over into the new one. These are the steps to follow:
1. Register your custom dialogs in Startup.cs
1. Update the routing logic in MainDialog.cs to route to your dialogs appropriately
1. Update your responses to use LG instead of the 0.3-beta JSON files.
1. Update appsettings.json with the values from your existing Azure resources
1. Update the cognitivemodels.json file to point to your existing dispatch model, LUIS models, and qna knowledgbases.
1. Connect your skills using the [botskills CLI](https://microsoft.github.io/botframework-solutions/skills/handbook/botskills/) tool and pointing to the new endpoints of your updated skills

These would be the steps I would follow for this migration. Please let me know if there are any other considerations I should take into account, or if you have any questions about how to do any of these steps in detail. I am happy to elaborate wherever needed.

**Comment by ipraveenMS** [comment]
@lauren-mills My question was specifically about how to seamlessly upgrade (without downtime) . I am in the middle of another work and I will get back to this and write a thorough reply soon.

**Comment by peterinnesmsft** [comment]
Hi @ipraveenMS,

Ultimately, our final stance here is that this is not something that we formally support. @lauren-mills has provided good guidance based on the initial outlined issue. We appreciate that this is a complex situation for you to work through for your individual case, but given our overall stance that this is not a formally supported scenario by the team as we have not had sufficient demand for this from other customers to warrant we support it, then I don't expect there is much more we will do here.

As a result, we will be closing this issue. If you have any particular questions about how to utilize any of our particular offerings, I would direct you to our Stack Overflow page, where our support team and others can help provide guidance on general questions around utilization of the Virtual Assistant solution accelerator and the underlying Bot Framework SDK, which you can find here: https://stackoverflow.com/search?q=bot+framework

Thank you for your understanding.
