### ISSUE TITLE
Deploy Cognitive Service powershell script qna mix languages ?

### ISSUE THREAD

**Issue by edemehmetcan** [microsoft/botframework-solutions#3606]
What project is affected?
Deployment script

What language is this in?

Powershell 

What happens?

Resources/QnA folder has 2 folders "fr-fr" and "en-en". After launching the deploy.ps1, a QnA resource is created an ALL  knowledge bases are put it on. So the new QnA resource present different language in one endpoint. 

Normally a QnA resource need to be created  per language and the specific .qna files need to be uploaded in the good endpoint.

What are the steps to reproduce this issue?

Create a knowledge base
Export it in Resources/QnA folder with specific language folder
Launch deploy.ps1 script
Inspect the resultant in qnamaker.ai, an endpoint has different language knowledge bases. 

Normally when you create knowledge base manually on the portal qnamaker.ai and you choose the language with the 1st knowledge base and after you want to create another one you need to chose the same language as the first knowledge base and not a different one. 

What were you expecting to happen?
Different QnA endpoint per language

Can you share any logs, error output, etc.?
Any screenshots or additional context?

**Comment by peterinnesmsft** [comment]
@edemehmetcan apologies for the delay on this. I am prioritizing this today and will get back to you later this afternoon.

**Comment by peterinnesmsft** [comment]
@edemehmetcan thanks for your patience while I've looked through this. Ultimately, the behavior you have described is by design.

One of the issues that we had faced in the past with QnAMaker using the approach mentioned was the high volume of overlapping resources that were created on behalf of the user in their Azure Subscription.

The other consideration is also around the associated Azure Search resource for the QnAMaker account. As things stand, there is an upper limit of how many Search resources can be created per subscription, and we had cases with customers in the past where they would hit issues due to hitting the upper limit of Search resources in their subscription.

As a result of these factors, we opted to design our provisioning scripts in such a way that minimized the number of generated resources to help provide a simpler and cheaper cost for users to manage them.

If your personal preference is to have separate resources, then we encourage you to make suitable modifications to the provisioning script, or create a QnAMaker knowledgebase through the portal and manually connect it to your Virtual Assistant. As there has not been a compelling use case from a significant enough volume of our overall customer base, we are unlikely to make a change here any time soon.

Let me know if you have any further questions or if there is anything else I can assist with.

**Comment by edemehmetcan** [comment]
@peterinnesmsft firstly thanks for your time to answer my question. I understand the way of "minimal cost" but normally as I know you have to create several QnA Maker Service/Search Service in Azure, one for each language, right? (Currently, the script is creating a knowledge base with many languages inside).

On my side, I have changed the script in order to have 2 separated resource (QnaHost/Search Service) one per language (french and dutch).
