### ISSUE TITLE
[Docs] Ambiguities in the docs (Project does not have a "wwwroot" folder; How to publish?)

### ISSUE THREAD

**Issue by bhdzllr** [microsoft/botframework-solutions#3638]
/skills/tutorials/create-skill/typescript/5-update-manifest/

I followed the steps from the TS create skill tutorial and in step 5 there are some ambiguities.

* I can not find a folder wwwroot in my project. Of course, there is a "src/mainfest/" folder with a "mainfest-1.0.json" sample file in it. But when I deploy or publish I can not access the manifest from the browser. There is just a 404 JSON response `{"code":"ResourceNotFound","message":"/manifest/manifest-1.1.json does not exist"}`
* Step 2: It is hard to know what exactly is `{YOUR_SKILL_URL}`, where did I defined it? Previous steps only talk about "name" or "id". Can I find it in the "appsettings.json"? Did the deployment script create it for me?
* Step 3: How to publish? There are no instructions how I should publish my changes. Guess you should not call the Deploy-Script from https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/typescript/4-provision-your-azure-resources/ instead call ".\deployment\scripts\publish.ps1"? And if i call the publish script where can I find the values the script asks for?
* Page about adding the skill https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/typescript/7-add-your-skill/ says that the localhost mainfest URL is `http://localhost:3978/src/manifest/manifest-1.1.json` which also does not work. n addition on my machine localhost is on port 3980.
EDIT: Just found two other issues mentioning the "manifest.json" problem #3600 and #3601 (with a pull request from August 3rd)

**Comment by Batta32** [comment]
Thanks @bhdzllr for reporting this issue! We will be reviewing this and we will back to you as soon as we have any update.

**Comment by lauren-mills** [comment]
We're adding this to the backlog to improve the TS docs around skills and publishing. Thanks!

For your question about publishing, you are correct that you can use the publish.ps1 script to publish, and you should be able to find the values for the resourceGroup and botWebAppName in your appsettings.json file after running the deploy.ps1 script.

**Comment by Batta32** [comment]
Hi @bhdzllr, we created the PR #3643 fixing the ambiguities that you mentioned above. Feel free to add your feedback in the Pull Request.

1. In TypeScript, the manifest is present in `src/manifest` but it throws an error if you try to access it fixed in the PR #3601. You can add those changes in the `index.ts` of your Skill to have access to the manifest.
1. `YOUR_SKILL_URL` is the endpoint URL where the Skill will receive the message (e.g. `http://localhost:3980/api/messsages`)
1. As @lauren-mills mentioned, you can use the `publish.ps1` and you can find the `botWebAppName` and `resourceGroupName` populated in the `appsettings.json` file after the deployment of the Skill
1. The PR #3601 fixes the access to the Skill's manifest, you can replicate those changes in your TypeScript Skill! Those changes will be incorporated in the next branch as soon as is merged. The correct path is `http://localhost:3980/manifest/manifest-1.1.json` after adding the changes of the Pull Request

We will be attentive to your answer 😊.

**Comment by GeoffCoxMSFT** [comment]
@peterinnesmsft - Please drive this PR to closure to resolve this issue.

**Comment by Batta32** [comment]
This issue is solved with PR #3643.
