### ISSUE TITLE
[Docs] wrong example

### ISSUE THREAD

**Issue by rodrigoratan** [microsoft/botframework-solutions#3649]
/skills/samples/restaurant-booking/

the example shows chinese and italian restaurants, the user choose the second one and the bot replies "chinese sounds great" !!! (facepalm)

**Comment by Batta32** [comment]
Thanks @rodrigoratan for reporting this issue, we confirmed what you mentioned in the attached image of the [/skills/samples/restaurant-booking/](https://microsoft.github.io/botframework-solutions/skills/samples/restaurant-booking/) document.

We will review the behavior of the [RestaurantBooking Skill](https://github.com/microsoft/botframework-skills/tree/master/skills/csharp/experimental/restaurantbookingskill) in order to update the documentation. As soon as we have any update, we will back to you later 😊.

**Comment by Batta32** [comment]
Hi @rodrigoratan, sorry for the delay. We created the PR #3658 which updates the wrong example in the document you mentioned.

Feel free to add your feedback!
