### ISSUE TITLE
update_cognitive_models.ps1 - dispatch refresh failed with Exit Code 1 Error in Deployment Automation

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-solutions#3662]
Something that I did not figure out returns exit code 1 in this command and gets caught by the deployment automation engine thus blocked the further execution.

update_cognitive_models.ps1
```json
dispatch refresh `
                --gov $useGov `
                --version $dispatch.version `
                --dispatch $dispatchFile `
                --dataFolder $(Join-Path $dispatchFolder $langCode) 2>> $logFile | Out-Null
```

**Workaround**: Removing the ` 2>> $logFile ` part from the command, but keep the `| Out-Null` to ensure not printing secrets to the console log.

**Comment by Batta32** [comment]
Thanks @dawwa for reporting the issue, we will try to reproduce the issue first and as soon as we have any update here we will back to you 😊.

Also, we will review the workaround that you mentioned of removing the `2>> $logFile` but keep the `| Out-Null`.

**Comment by Batta32** [comment]
Hi @dawwa - sorry for the delay. We successfully **reproduced** the issue of Exit Code 1 executing the `update_cognitive_models.ps1` script in a pipeline.

We will be checking the best approach to solve this, as soon as we have any update, we will back to you here 😊.

_Exit code error 1_
![image](https://user-images.githubusercontent.com/11904023/94451266-901c0b80-0184-11eb-94cf-ff0b822b8f94.png)

**Comment by Batta32** [comment]
@dawwa - we successfully **confirmed** that the workaround you suggested (remove `2>> $logFile`) works for the `update_cognitive_models.ps1` execution.

We researched about the `2>> $logFile` implementation that basically logs all the error output of a specific command inside the log file:
- `2`: error stream
- `>>`: append specified stream to a file
- `$logFile`: is the `update_cognitive_models_log.txt` log file

We will research if it's the best approach to follow and as soon as we have any update, we will back to this issue.

Documentation:
- [PowerShell redirection operators](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-7)
- [What does '>>' do in powershell?](https://stackoverflow.com/questions/35088340/what-does-do-in-powershell)

![image](https://user-images.githubusercontent.com/11904023/94463909-10963880-0194-11eb-8c64-057fbd55da88.png)

![image](https://user-images.githubusercontent.com/11904023/94463943-17bd4680-0194-11eb-9b61-892d61c5bc40.png)

**Comment by Batta32** [comment]
Hi @dawwa, we **raised** the issue microsoft/botbuilder-tools#1474 as we found that the problem is how dispatch refresh manages the Error Stream. Also, we created the PR #3675 adding a new [known issue](https://microsoft.github.io/botframework-solutions/help/known-issues/) with this scenario.

As a **workaround** you can change the `ErrorActionPreference` to `Continue` of the PowerShell task that executes the `update_cognitive_models.ps1`.
``` powershell
$ErrorActionPreference = 'Continue'
```

Last but not least, we successfully **reproduced** the same issue isolating the dispatch refresh execution from the `update_cognitive_models.ps1` and having configured the `$ErrorActionPreference` as `Stop` in PowerShell.

To accomplish this, we followed these steps:
1. Have a deployed dispatch
1. Open a new instance of PowerShell
1. Configure $ErrorActionPreference as Stop
   ``` powershell
   $ErrorActionPreference = 'Stop'
   ```
1. Execute the dispatch refresh with hardcoded values
   > dispatch refresh --version Dispatch --dispatch "<PATH_TO_DISPATCH_FILE>" --dataFolder "<PATH_TO_DISPATCH_FOLDER>" 2>> "<PATH_TO_LOG_FILE>" | Out-Null
1. See that the dispatch refresh is stopped and the log file doesn't contain any output

We will be attentive to your reply 😊.

**Comment by Batta32** [comment]
@peterinnesmsft - we can close the issue due to inactivity. We added the explanation in the [Known Issues](https://microsoft.github.io/botframework-solutions/help/known-issues/#dispatch-refresh-failed-with-exit-code-1-error-using-erroractionpreference--stop-in-powershell) document and how to solve it.
