### ISSUE TITLE
Errors in deployment of Virtual Assistant template project

### ISSUE THREAD

**Issue by veatcha** [microsoft/botframework-solutions#3695]
#### What project is affected?

Project created from Virtual Assistant template in VS Community 2019 (16.7.6) 

#### What language is this in?

C#

#### What happens?

Failures occur during QnA cognitive model deployment, Azure resources and steps were successful up to this point.  Continued failures with retry occured during the QnA steps, I cancelled the deployment script and checked the logs.

#### What are the steps to reproduce this issue?

Followed steps here exactly: 
https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/1-intro/

- Running Windows 10
- Installed Virtual_Assistant_and_Skill_Templates.4.9.1.2.vsix
- Commands run in an elevated PS window (7.0.3), Azure CLI 2.14.0

#### What were you expecting to happen?

Deployment to complete without errors...

#### Can you share any logs, error output, etc.?

From `deploy_cognitive_models_log.txt`:

AZ CLI passes minimum version. Current version is 2.14.0
test-virtual-assistant-boten-us_Dispatch.dispatch created
[ERROR] Error happened when parsing qna section: Invalid regular expression: /^```(markdown)?\r*\n(?<answer>(.|\n|\r\n|\t| )*)\r?\n.*?```$/: Invalid group
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
[ERROR] Error happened when parsing qna section: Invalid regular expression: /^```(markdown)?\r*\n(?<answer>(.|\n|\r\n|\t| )*)\r?\n.*?```$/: Invalid group
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Faq.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Faq.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Faq.json'

#### Any screenshots or additional context?

Confirmed those json files referenced in errors do not exist - there are .qna files present in those directories however.

**Comment by Batta32** [comment]
Hi @veatcha, thanks for reporting this issue. We came up with some **questions** in order to narrow the problem as we couldn't reproduce the issue currently.
1. Are you using [@microsoft/botframework-cli@4.10.1](https://www.npmjs.com/package/@microsoft/botframework-cli/v/4.10.1)?
1. Have you tested to deploy the C# Virtual Assistant again?
1. Do you face this issue in every attempt to deploy?
1. Are you executing the `deploy.ps1` being in the root folder of the C# Virtual Assistant?
1. Is this issue only present in the C# Virtual Assistant?
1. Have you tried to deploy a C# Skill?

The `.json` files are created after executing [bf qnamaker:convert](https://www.npmjs.com/package/@microsoft/botframework-cli#bf-qnamakerconvert) in [qna_functions.ps1](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/qna_functions.ps1#L9) having the [collection](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1#L257) of `.qna` files present in `Deployment\Resources\QnA\<language>`.

As soon as we have any update, we will back to you later 😊.

_.json files created from .qna files during deployment_
![image](https://user-images.githubusercontent.com/11904023/97577113-bde7b080-19cd-11eb-9062-dcb5b6650a20.png)

_Successful deployment of a C# Virtual Assistant created from the VSIX_
![image](https://user-images.githubusercontent.com/11904023/97577221-e4a5e700-19cd-11eb-85f3-245560953f52.png)

**Comment by veatcha** [comment]
Hi - Thanks for the followup - 

- Confirmed I am on botframework cli 4.10.1
- I have tried 3 times now, and have had the same result each time (I've copied the output from most recent run below)
- I am executing the deployment command from the project folder - that's shown below as well.  The obnoxious folder nesting is the repo folder/solution folder/project folder all with same name.
- I have not tried deploying a different bot template or a skill project yet, but can.

Trying to follow the thread of the error message regarding the RegEx with an invalid group but can't find where that Regex is maintained in this repo...

botframework cli version:

![image](https://user-images.githubusercontent.com/3845306/97606531-44a88780-19e6-11eb-9f21-7d9cfeffb839.png)


Command output:

![image](https://user-images.githubusercontent.com/3845306/97606027-b59b6f80-19e5-11eb-9f50-076618521c83.png)

**Comment by veatcha** [comment]
@Batta32 - found the issue here.  My node version was set to less than the required version for the botframework cli, and it looks like that was impacted RegEx behaviors.  Thanks.

**Comment by VictorGrycuk** [comment]
Hi @veatcha, thanks for let us know, we found the issue microsoft/botframework-cli#865 which had the same error message as you described above, and the response was to update the Node version as `bf-cli` requires [node version >= 10.14.1](https://github.com/microsoft/botframework-cli#installation). 

Thank you for your time. 🙂
