### ISSUE TITLE
[Botskills] unnecessary code in connect and failed tests

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3700]
#### What project is affected?

Botskills

#### What happens?

1 this if block is unnecessary and incorrect (should be trim()):
https://github.com/microsoft/botframework-solutions/blob/4d23f882776d4a730770e3576f660d629ee92360/tools/botskills/src/functionality/connectSkill.ts#L110

2 `npm test` is broken. We should add this to pipeline

**Comment by Batta32** [comment]
Hi @xieofxie, thanks for reporting this issue!

The `luFile.trim.length` was correctly replaced to `luFile.trim().length` in the PR #3534. However, we will analyze the validation in order to check if it's necessary or not.

Also, we confirm that the unit tests are correctly working using [next](https://github.com/microsoft/botframework-solutions/tree/next) branch, to test it you can follow these steps:
1. Go to [botskills](https://github.com/microsoft/botframework-solutions/tree/next/tools/botskills) folder
1. Execute `npm install` to install the dependencies
1. Execute `npm run build` to compile the solution
1. Execute `npm run test` 
1. Check that the tests are correctly passing

Finally, we will start working to improve the logic of the tool and we will back to you as soon as we have any update.

_Successful execution of npm run test using next branch_
![image](https://user-images.githubusercontent.com/11904023/97998343-bc045f80-1dc8-11eb-808d-1e50ba6f92a2.png)

**Comment by xieofxie** [comment]
Thanks! I will check the next branch~

**Comment by peterinnesmsft** [comment]
As it looks like this has ultimately been addressed and is pending release of new bits from next branch, closing this out. If issues are discovered with the new bits, then we can reactivate and investigate further.
