### ISSUE TITLE
Deploy cognitive models script not working in azure devops pipeline

### ISSUE THREAD

**Issue by VidhyaSanjeevi** [microsoft/botframework-solutions#3712]
#### What project is affected?
VA

#### What language is this in?
En

#### What happens?
Times out 

#### What are the steps to reproduce this issue?
Execute the VA deploy cognitive models PS1 file in azure CLI task

#### What were you expecting to happen?
Luis and qna deployment sucess

#### Can you share any logs, error output, etc.?
No logs, pipeline executes for half ab hour no logs at all times out in pipeline.

#### Any screenshots or additional context?
Tried executing in azure powershell task it executes partially the input parameters are not captured correctly 

Referred this but no success.
Note : I am executing deploy cognitive models script directly
https://stackoverflow.com/questions/56267466/deploy-virtual-assistant-using-azure-devops-pipelines-and-releases

**Comment by Batta32** [comment]
Thanks @SSanjeevi for reporting this issue! We came up with some **questions** for you:

1. Have you updated the `Build job timeout in minutes` of your Azure DevOps Pipeline? Try improving the amount of minutes for the job
1. Have you tested the execution of the `deploy_cognitive_models.ps1` script locally?

We will be reviewing this issue and as soon as we have any update, we will back to you 😊

_Set 240 minutes for Build job timeout in minutes_
![image](https://user-images.githubusercontent.com/11904023/99802453-7b218000-2b16-11eb-950a-a50605a0a0f3.png)

**Comment by VidhyaSanjeevi** [comment]
Will it run for 240 minutes?

I kept for 90 minutes in pipeline and it didn't gave any cli msg till that and times out .
Will test by keeping 240 minutes on Monday.
Local it completes in 15 mins I seen.

**Comment by VidhyaSanjeevi** [comment]
@Batta32 - i tried setting for 240 minutes and it got timed out at 240 minutes and only one line came in cli:
"Initializing en-us dispatch model"

screenshot below.

do you want me to further increase the timeout? - then i must try in non office hours like yesterday.

![image](https://user-images.githubusercontent.com/24915474/100052781-a4a71800-2e44-11eb-9bbb-3e85a44fe030.png)

**Comment by Batta32** [comment]
Hi @SSanjeevi, it's not necessary to increase the `timeout` as the script should not be executed for a long time.

1. Can you share the tasks/commands that you are executing in the Azure Pipeline? So we can replicate it in our environment
1. Which versions of [botdispatch](https://www.npmjs.com/package/botdispatch) and [botframework-cli](https://www.npmjs.com/package/@microsoft/botframework-cli) are you installing in the Azure Pipeline?
1. Have you tried to execute another deployment script? For example the `deploy.ps1` instead of the `deploy_cognitive_models.ps1`. Which was the result?

We will work on this issue this week, so as soon as we have any update for you we will let you know here.

**Comment by Batta32** [comment]
Hi @SSanjeevi, as we discussed over email, we managed to **reproduce** and **solve** the issue using an Azure DevOps Pipeline and the YML file you attached in the email.

We applied the following changes using the YML file you attached:
- Add a task to install Node version 12.16.1: we added this task to avoid the INVALID_ALT_NUMBER warning (see microsoft/botframework-cli#1059).
- Replace the AzureCLI@2 task for a PowerShell one: we think that this was the root cause that the execution was taking so much time to be finished.

If you are ok, we can close this issue 😊.

_Correct YML file successfully working_ 
![image](https://user-images.githubusercontent.com/11904023/101189405-c61eb580-3635-11eb-9cbd-e801371f3687.png)
