### ISSUE TITLE
How do we know the skills works?  What should we expect it to return?

### ISSUE THREAD

**Issue by jcbendernh** [microsoft/botframework-solutions#3713]
/skills/tutorials/create-skill/csharp/8-invoke-your-skill/

**Comment by Batta32** [comment]
Hi @jcbendernh, after the connection of the Virtual Assistant to the Skill you can see how the `botFrameworkSkills` and `skillHostEndpoint` properties of the Virtual Assistant's `appsettings.json` file are populated with the values of the Skill's manifest.

The **expected** behavior is: while you are testing the communication, you can send an utterance from the Virtual Assistant that should be recognized by the Skill and see how the Skill starts the necessary workflow, and when the Skill is finished it will send the control back to the Virtual Assistant.

Also, we will improve the [/skills/tutorials/create-skill/csharp/8-invoke-your-skill/](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/8-invoke-your-skill/) in order to show a specific scenario of this connection.

We will add these changes in the PR #3710.

**Comment by Batta32** [comment]
Hi @jcbendernh, we already applied the changes in the PR #3710 (see [commit](https://github.com/microsoft/botframework-solutions/pull/3710/commits/dc6df47ab910dfbcb4c444020527119f3605e9f3)).

Feel free to add your feedback in the PR!

**Comment by Batta32** [comment]
We applied the necessary changes in the PR #3710 (see [commit](https://github.com/microsoft/botframework-solutions/pull/3710/commits/dc6df47ab910dfbcb4c444020527119f3605e9f3)).
