### ISSUE TITLE
Multi-turn QnA results in error

### ISSUE THREAD

**Issue by pdesai-icims** [microsoft/botframework-solutions#3765]
#### What project is affected?
Virtual Assistant
#### What language is this in?
C#
#### What happens?
Using QnA Multiturn on Teams. Virtual assistant correctly identifies the first prompt but later prompts(multiturn)are resulting in error.
#### What are the steps to reproduce this issue?
Asking the question with Multi turn prompt will result in errors in subsequent prompts.
#### What were you expecting to happen?
Expecting to the conversation to flow through the multiturn as general.

**Comment by Batta32** [comment]
Hi @parasdesaicims, thanks for reporting this issue.

We will tackle this issue the next week and as soon as we have any update, we will back to you here 😊.

**Comment by Batta32** [comment]
Hi @parasdesaicims, we couldn't reproduce the issue as we **were able** to execute the multi-turn QnA in MS Teams channel. We found that multi-turn QnA was added in the PR #2809.

To accomplish this, we followed these **steps**:
1. Create a new Knowledge Base from the [QnAMaker Portal](https://www.qnamaker.ai/)
1. Enable the option `Enable multi-turn extraction from URLs, .pdf or .docx files`
1. Populate the Knowledge Base from URL, PDF or DOCX
1. Publish the Knowledge Base
1. Add the Knowledge Base into the C# Virtual Assistant
1. Execute the Virtual Assistant in MS Teams Channel
1. Send an utterance to execute the multi-turn QnA
1. Verify its correct execution

We used as a guide the following documents:
- [Add an additional Knowledge Base](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/)
- [Use follow-up prompts to create multiple turns of a conversation](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/multiturn-conversation#create-a-multi-turn-conversation-from-a-documents-structure)

Finally, we confirmed that in the Bot Framework Emulator works correctly.

Let us know if this helps you 😊.

_Multi-Turn QnA correctly working in MS Teams_
![mulit-turn-teams](https://user-images.githubusercontent.com/11904023/108754947-609be000-7525-11eb-884e-7d9ac88af8e1.gif)

**Comment by pdesai-icims** [comment]
Thanks, @Batta32. here is the issue in detail : 

**What happens**
When a user joins the conversation he is welcomed with the message which prompts for a couple of QnA's we have in the dispatch. There are a couple of buttons which has an action set configured for _MS teams_

> {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "title": "Tell me about Okta",
                            "data": {
                                "msteams": {
                                    "type": "messageback",
                                    "displayText": "Tell me about Okta",
                                    "text": "echo to the Chat stream: tell me something about Okta"
                                }

The bot is correctly predicting the question and prompts the response for it correctly. But its getting a turn error when clicked any button in the follow-up prompt:
![Bot welcome user](https://user-images.githubusercontent.com/56562244/108874261-fd17be00-75c9-11eb-854d-08a4104d5b55.gif)

- Bot Welcome message: **Adaptive card in mainresponse.lg**
- Okta FAQ message:  **QnA maker kb under dispatch as q_qna**
- Multiturn: **within the same QnA maker kb**

Multiturn works fine in QnA Maker and the intent is correctly identified with LUIS : 



**What were you expecting to happen?**

The user is welcomed with the Adaptive cards containing buttons of some submit tasks. These buttons when clicked would be used as questions from the user, which in turn should provide answers from the QnA Maker. Also, if multiturn it should check LUIS intent before continuing the conversation in providing the answer.

Attaching the transcript as well.
[Multiturn issue.transcript.zip](https://github.com/microsoft/botframework-solutions/files/6030434/Multiturn.issue.transcript.zip)

**Comment by Batta32** [comment]
@parasdesaicims - thanks for this detailed comment. We will be reviewing the attached information and let you know any update 😊.

**Comment by Batta32** [comment]
Hi @parasdesaicims, we successfully **solved** the issue following the [document](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/) (`Add an additional knowledge base` -> `Step 4`). We created the PR #3768 as we noticed that the `Step 4` is not clear enough to understand which changes should be added in the `MainDialog`.

We created the [feature/southworks/fix-issue-3765](https://github.com/southworks/botframework-solutions/tree/feature/southworks/fix-issue-3765) branch which contains the changes needed to accomplish the Step 4.

The **steps** we followed to solve the issue were:
1. Create a Knowledge Base with a Multi-Turn dialog
1. Update the C# Virtual Assistant cognitiveModels.json adding the new Knowledge Base
    ```json
     {
       "id": "YOUR_KB_ID",
       "name": "YOUR_KB_ID",
       "kbId": "",
       "subscriptionKey": "",
       "hostname": "https://YOUR_NAME-qnahost.azurewebsites.net",
       "endpointKey": ""
     }
    ```
1. Execute the `update_cognitive_models.ps1` to associate the Dispatch model with your new Knowledge Base
    ```bash
    ./Deployment/Scripts/update_cognitive_models.ps1 -RemoteToLocal
    ```
1. Update the Virtual Assistant's MainDialog to include the corresponding Dispatch intent for the new Knowledge Base
1. Execute the C# Virtual Assistant in Emulator
1. Check that the Multi-Turn flow works correctly

_Multi-Turn workflow_
![mulit-turn-issue3765](https://user-images.githubusercontent.com/11904023/109058707-1734c780-76c2-11eb-9034-52f3d79d6644.gif)

_Issue reproduced_
![image](https://user-images.githubusercontent.com/11904023/109058176-6fb79500-76c1-11eb-863a-ca673e069303.png)

Let us know if this helps you 😊.

**Comment by pdesai-icims** [comment]
@Batta32  I found the same workaround and was about to post this. Glad it's already taken care of. I have taken care of the same for my local VA. Though I am having one more request, not sure if this will be part of this or not it's definitely related to multiturn : 

> The dialog if there is a multiturn QnA, sticks to that multiturn unless a. the question asked is from the same QnA kb or any intent from Interrupt Dialog is called (cancel, help, etc.). Technically if we include all the intents within the Dispatch to act as an interruption to the dialog, so that no matter the question of user, Interruption would follow through and provide the user with correct information instead of an error or repeating the same dialog.

*Example of it*
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/56562244/109062802-6543ce00-76b6-11eb-9baf-997b748fe0c0.gif)

Please let me know if this helps or I am missing out on something which is already there in documentation. **Appreciate all your help.**

**Comment by Batta32** [comment]
Hi @parasdesaicims, as far as we understood following your last [comment](https://github.com/microsoft/botframework-solutions/issues/3765#issuecomment-785360248), you want to handle different ways to [interrupt](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs#L201) the Multi-Turn Knowledge Base. If so, **by design** the only way to interrupt a dialog is through the intents Cancel, Help, Escalate, etc. But that could be changed and it's depends on each environment.

We **recommend** you the following documentation:
- [Handle interruptions](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-conversation-flow?view=azure-bot-service-4.0#handle-interruptions)
- [Handle user interruptions - Bot Service | Microsoft Docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-handle-user-interrupt?view=azure-bot-service-4.0&tabs=csharp)

Those documents explains how to handle the dialogs' interruption, and you will be able to apply the corresponding modifications according to your environment.

If this is not your problem, please can you explain your problem detailing it? (e.g. `transcript` file)

We hope this helps you 😊.

**Comment by pdesai-icims** [comment]
Assume there are two QnA KB attached to a VA - FAQ, and Qnamaker. There are some answers with Multiturn and some without.

*Without multiturn* 
> If a question is asked about FAQ that is returned. If 2nd question is asked about Qnamker that is returned. Both correctly identified intents on LUIS and the correct answers returned.

*With multiturn*
> If a question is asked about FAQ, the returned answer is multiturn. Now if 2nd question is asked from Qnamaker kb, the LUIS trace shows correct intent identified but the answer returned is from FAQ kb. 

I hope this is not by design as understanding the context of the user is important to be the question is multiturn or not. Please let me know if you need screenshots or further information.

*Appreciate your time & help!* :)

**Comment by Batta32** [comment]
Thanks @parasdesaicims for the detailed comment, we will work on the described scenario and we will let you know any update we have 😊.

**Comment by Batta32** [comment]
Hi @parasdesaicims, we successfully found a **workaround** after reproducing the issue. If you want to customize the interruptable actions, you should update the [InterruptDialogAsync](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs#L201) as mentioned in the [comment](https://github.com/microsoft/botframework-solutions/issues/3765#issuecomment-786141994).

For your scenario, add the FAQ intent inside the `InterruptDialogAsync` to be recognized as interruptable. We updated the shared [branch](https://github.com/southworks/botframework-solutions/tree/feature/southworks/fix-issue-3765), adding the [commit](https://github.com/southworks/botframework-solutions/commit/970d6ef04da662eca65134ace4fc2d0d716f11d7) so you can see the necessary changes.

**By design**, the Virtual Assistant is interrupted if:
1. The intent is recognized to switch between skills
1. The intent is recognized as a General LUIS (Cancel, Escalate, etc)

As an additional information, see the [Activity Flow](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/activity-flow/#dialogs) document.

_Interruptions_
![image](https://user-images.githubusercontent.com/11904023/109544650-95201680-7aa6-11eb-92bf-137571d7ae53.png)

_Multi-Turn interrupted by a FAQ intent_
![mulit-turn-issue3765-interrupt](https://user-images.githubusercontent.com/11904023/109544278-1f1baf80-7aa6-11eb-9b97-63c5a51d50f1.gif)

**Comment by pdesai-icims** [comment]
Thank you for the details here, @Batta32. 

Even after the changes, it is still stuck in that multi-turn dialog. Please find the attached screenshots below. 

_The changes within InterruptDialogAsync method_ 

> ![Screen Shot 2021-03-02 at 11 41 47 AM](https://user-images.githubusercontent.com/56562244/109683307-3bbef280-7b4d-11eb-8538-9f2d4e866db5.png)

_Starting the dialog with Multi-turn - intent q_qnamaker_ 

> ![Screen Shot 2021-03-02 at 11 41 21 AM](https://user-images.githubusercontent.com/56562244/109683424-54c7a380-7b4d-11eb-8142-0b523d4fcbf6.png)

_Interrupting dialog with other intent - q_faq (intent is correctly identified but still the same response._

> ![Screen Shot 2021-03-02 at 11 45 45 AM](https://user-images.githubusercontent.com/56562244/109683563-7759bc80-7b4d-11eb-9298-159a0ed57a7e.png)

I believe this works, this would also interrupt the normal flow of dialog, and simple conversation (qna) will never happen with the bot. _Correct me if I am wrong._
Please check and let me know if you need more information. Appreciate your time and help. :)

**Comment by Batta32** [comment]
Thanks @parasdesaicims, we came up with some **questions**:
1. Can you check if the added code in the `InterruptDialogAsync` method is executed? If so, all the dialogs should be cancelled and you should see the `CancelledMessage` activity.
2. Which should be the expected response of the `what is iBOT`? Can you attach an image?
3. Can you share a reduced branch of your environement/code so we can reproduce the issue on our side?

Adding the `q_Faq` model as interruptable should stop the Multi-Turn Dialog.

_The highlighted arrows should be the happy path to interrupt the Multi-Turn dialog_
![image](https://user-images.githubusercontent.com/11904023/109700441-7f772380-7b70-11eb-8eff-f2d215ceaee4.png)

**Comment by pdesai-icims** [comment]
Yes, so I was able to update the code. It was my silly mistake but after that, as I figured that the happy path to interrupt is being followed for all the conversation whenever the q_faq intent is matched.

_Multiturn - Dialog interrupted as expected_
>![Screen Shot 2021-03-02 at 2 16 07 PM](https://user-images.githubusercontent.com/56562244/109702549-5f406800-7b62-11eb-9f63-749780359f67.png)

_Dialogs with q_faq intent getting Cancelled_
>![Screen Shot 2021-03-02 at 2 17 19 PM](https://user-images.githubusercontent.com/56562244/109702622-78491900-7b62-11eb-9a58-98940f5c436b.png)

_Breakpoint showing the flow and entering "else if" block as the intent is matched_
>![Screen Shot 2021-03-02 at 2 19 44 PM](https://user-images.githubusercontent.com/56562244/109702672-87c86200-7b62-11eb-98c5-8dfb073ed258.png)

**Comment by Batta32** [comment]
@parasdesaicims - Exactly, that's because the `faq` is not executed, but only recognized as interruptable.

To execute the FAQ when it's interrupted, you should customize the added code to execute what you want. For example, we added this [commit](https://github.com/southworks/botframework-solutions/commit/32211ee548cab1484c24c5c7ad488571052a163e) in which you can see that the FAQ is executed when is recognized as interruptable.

**Comment by pdesai-icims** [comment]
@Batta32
 **_awesome, Thank you!_** 
The approach on my end was wrong, I was looking to interrupt rather than continue the conversation, appreciate your detailed input here it helped. Cool! so now 3 kb are being handled with multiturn.

Is there any detailed documentation about the [SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.adaptive.conditions.oncondition.executeasync?view=botbuilder-dotnet-stable#Microsoft_Bot_Builder_Dialogs_Adaptive_Conditions_OnCondition_ExecuteAsync_Microsoft_Bot_Builder_Dialogs_Adaptive_ActionContext_), maybe that would be helpful?

**Comment by Batta32** [comment]
Awesome @parasdesaicims , we are happy to help you on this. I'm **closing** this issue as it's solved.

I'm attaching the main documentation of botframework (specially in Dotnet):
- [botframework-sdk repository](https://github.com/microsoft/botframework-sdk)
- [botbuilder-dotnet repository](https://github.com/microsoft/botbuilder-dotnet)
- [Azure Bot Service documentation](https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0) of Dotnet
- [Available packages](https://github.com/Microsoft/botbuilder-dotnet/#packages) of Dotnet
- Dotnet [Samples](https://github.com/Microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore)
- [botframework-solutions documentation](https://microsoft.github.io/botframework-solutions/)

Feel free to open a new issue if you have a different problem!
