### ISSUE TITLE
Roadmap for Virtual Assistant

### ISSUE THREAD

**Issue by jhealy** [microsoft/botframework-solutions#3786]
**Please describe your request**
Can we get a roadmap of anything being planned for Virtual Assistant?   Thanks...

**Is this an issue with current documentation? If yes, please provide the link.**
No roadmap doc in current documentation, so no link available.  Thanks...

**Comment by darrenj** [comment]
Hi @jhealy 

We've been hard at work at infusing the Virtual Assistant work into Bot Framework Composer bringing bringing all of the capabilities/value of VA into Composer whilst at the same time simplifying the act of creating and authoring conversational experiences. We will deliver this work at Build but you can test some of the capabilities in Composer today by enabling early adopters/preview features and getting the latest build installed.

![image](https://user-images.githubusercontent.com/33519520/114679524-228c9280-9d04-11eb-9bc6-0df291ed27f1.png)

When you create a new project you'll see a new list of templates (names are TBC) - these are all based on a new bot runtime that brings all of the features that VA brought (e.g. speech support, multi-language, telemetry, routing, etc.)

![image](https://user-images.githubusercontent.com/33519520/114679689-5071d700-9d04-11eb-9b0c-f23dfcced6d6.png)

If you look at what's currently called Basic Assistant this is the best analogy to what we gave you in VA out of box, but now it's much easier to pick and choose the features (via packages) that you want meaning you can choose exactly what features you need. It doesn't matter if you start with a simple (blank/empty) bot as you can add these same packages to build up to something more complex. We'll also have a library of other packages containing helpful capabilities (e.g. human handoff).

Existing VA users, don't worry! You'll have some options, for those that have used the skill pattern and built extensions/customisations into skills you can go ahead and create a new Composer based root bot and connect those skills just as you have done before but now powered by Orchestrator instead of dispatch improving dispatch quality. Moving to a Composer root bot will reduce the amount of custom code you have to maintain and you'll benefit from more improved routing/activity handling. You can then bring any LU/LG enhancements across and can move forward.

If you have waterfall dialogs authored you can add these to a new Composer project and "begin" them as you would do Composer built dialogs.

Or - you can carry on with your "code first" path your on and invoke new experiences through Skills, and build these in Composer.

Hope this helps.

**Comment by jhealy** [comment]
Thank you.
