### ISSUE TITLE
[Docs] Unable to automate Azure Chatbot app with Azure DevOps which is using Virtual Assistant template

### ISSUE THREAD

**Issue by SujeetKulkarnii** [microsoft/botframework-solutions#3790]
Hello Team,

I am working on QnAMaker based Azure Bot App, the application works well in current state, but I am looking for automating Resource deployment through Azure DevOps.
There is document reference [https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-integration/csharp/3-create-yaml/] which shows steps, how to CI/CD bot app but I think the document missing few steps:
1) **In Continuous Integration we suppose to deploy resources executing deploy.ps1 script this part is not mentioned in yaml** 
or neither any step provided in build pipeline as shown in example. 	[https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-integration/csharp/3-create-yaml/]

2) Although I have tried running deploy.ps1 in build (CI) part but the script does not execute giving PowerShell error (I am using Azure PowerShell, this throws version compatibility issue), And if I use  PowerShell Core, it does not allow az login even with valid cred or at least giving hard time - This part also seems missing in the documentation

3) I am also wondering how CI part will persist or access variables created during deploy.ps1 script as it requires those variable information to update cognitive model for creating KB and other configuration. (this part also not mentioned anywhere or at least I couldn’t found.)
	
4) I also learned that we cannot use Read-Host in PS script, so how we can get inputs from pipeline, do  need to modify current ps1 ?
	
5) I also failed to understand how release pipeline access cognitive model script if artefacts are zipped

I have already referred one of the issue reported [https://github.com/microsoft/botframework-solutions/issues/3779]  , this solution is pretty close but I have failed to understand how deploy.ps1 is configured in build step and its variable is being referred in release step for updating cognitive model.

Is there any document reference to help me to understand complete deployment cycle, it would be grateful if I get one.
Or at least direct to address the concern.
Is there any possibility to make pipeline just for resource deployment and configuration and not as a part of .Net Core based ChatBot applicaiton. this way we can independently manager infrastructure (In many cases there will be very few changes in infrastructure but frequent changes in bot app source code)

**Comment by Batta32** [comment]
Hi @SujeetKulkarnii, thanks for reporting this issue. We will be collecting the correct information for you and we will let you know as soon as we have any update 😊.

**Comment by Batta32** [comment]
Hi @SujeetKulkarnii, we'd like to **differenciate** `Continuous Integration` vs `Continuous Deployment`.
- Continuous Integration: is an automation to build and test applications whenever new commits are pushed into the branch (changes in bot app source code)
- Continuous Deployment: deploy application to production without human intervention (infrastructure changes)

Now **answering** the attached questions:
1. The [solution-accelerators/tutorials/enable-continuous-integration/csharp/3-create-yaml](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-integration/csharp/3-create-yaml/) document contains the CI YAML following the CI's description of above. The deploy step is not part of the CI. Also the document mentions that the YAML file should be customized to the user's requirements, so you can update the YAML to integrate the deploy execution.
2. Have you tested using a PowerShell task executing the [az login](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az_login) before the `deploy.ps1` script? (see [example](https://github.com/microsoft/botframework-solutions/blob/next/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/Nightly-Dotnet-VirtualAssistantToSkill.yml#L203))
3. The [solution-accelerators/tutorials/enable-continuous-deployment/2-create-pipeline](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-deployment/2-create-pipeline/) explains how to configure the CD adding the values of your deployment in the release pipeline
4. It's not necessary to update the ps1 script. The [Read-Host](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/read-host?view=powershell-7.1) cmdlet reads a line of input from the console and in the pipeline can't be executed, those required variables should be attached in the Release Pipeline (e.g. MicrosoftAppId/MicrosoftAppPassword)
5. Having configured a C#/TypeScript bot is a Release Pipeline prerequisites (see [document](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-deployment/1-intro/)). Once you have deployed the bot, you can start configuring the Release Pipeline in order to populate the variables mentioned [here](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-deployment/3-configure-pipeline/). The goal of the Release Pipeline is to update the bot services using a pipeline and executing the [update_cognitive_models.ps1](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Deployment/Scripts/update_cognitive_models.ps1) script. In the step 6 mentions to create a PowerShell task to update the `cognitivemodels.json` stored in the artifact which be used to update the bot services

As a **summary**, the CI/CD documents of the repository mentions to separate the infrastructure and bot app source code changes in different pipelines, having one instance of  deployment in which the code will be confirmed by CI and the bot services will be updated by CD.

We collected these helpful documents for you:
- [Continuous integration vs. continuous delivery vs. continuous deployment](https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment)
- [Tutorial: Enable continuous integration (csharp)](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-integration/csharp/3-create-yaml/)
- [Tutorial: Enable continuous deployment](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-deployment/2-create-pipeline/)
- [Nightly-Dotnet-VirtualAssistantToSkill.yml](https://github.com/microsoft/botframework-solutions/blob/next/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/Nightly-Dotnet-VirtualAssistantToSkill.yml)

Hope this helps you 😊.

_Different stages to deploy to production_
![image](https://user-images.githubusercontent.com/11904023/116458835-74243980-a83b-11eb-8d75-947c26e3498c.png)

**Comment by SujeetKulkarnii** [comment]
Thank you @Batta32 for detailed explanation, there are several takeout from the above answer,
1) Very well differentiated CI / CD part (which i assumed i was aware of but was missing knowledge in context of BOT Deployment strategy)
2) Deploying BOT resources (infrastructure) and at the same time updating KBs configuration

I still feel, MS documentation could have been  more detailed or comprehensive, nevertheless i will explore more with provided inputs, 
Thank you for helping out here, i really appreciate that.
