### ISSUE TITLE
Bot Framework Emulator:  Invalid `applicationId` value detected

### ISSUE THREAD

**Issue by bml1g12** [microsoft/botframework-solutions#3845]
Going through the tutorial [here](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/typescript/5-run-your-assistant) using Linux, so I cannot use the powertools deployment script provided and manually deployed resources. When running `npm run start` I get: 

```
Error: Invalid `applicationId` value detected: 
Please make sure your applicationId is a valid LUIS Application Id, e.g. "b31aeaf3-3511-495b-a07f-571fc873214b".
```

I have entered the LUIS application id 
![image](https://user-images.githubusercontent.com/2605767/137951533-6a9b2b82-7b5f-4cba-9f43-fcc31b2e1173.png)
As the 
  "microsoftAppId": 
In `src/appsettings.json` of the sample deployment on my machine. Am I doing something wrong here?

Albeit I am unsure what the password should then correspond to. I thought maybe the microsoftAppId and microsoftAppPassword should instead correspond to the Application (client) ID  and Client Secret I created [here](https://docs.microsoft.com/en-us/previous-versions/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0&tabs=aadv1#register-an-application-in-azure-ad).
Overal a bit confused by [this](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/deploy-assistant/web/4-update-application-settings/) step of the tutorial - many thanks for any help.

**Comment by lauren-mills** [comment]
Hi @bml1g12, the microsoftAppId in appsettings should the the id of the Microsoft App Registration created when you provisioned your bot in Azure. This Id and Pw can be found in the Azure Bot > Configuration tab in the Microsoft App ID field. To find your app password, click the "Manage" button beside this field to navigate to the app registration details. The password can be found/updated in the Certificates & secrets tab under Client secrets.

For your LUIS app ID shown above, this should be in the appId field for each individual LUIS model in your cognitivemodels.json file. 

Since you are creating your appsettings and cognitivemodels settings manually, here are two samples of those files so you can see the schema if you haven't already: [appsettings.json](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-assistant/src/appsettings.json), [cognitivemodels.json](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-assistant/src/cognitivemodels.json)
