### ISSUE TITLE
POI should default country based on location rather than locale.

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#449]
**Project**
Skills, POI

**Description**
PointOfInterestSkillDialog has "US" hadcoded for country (which it shouldn't) but even after that, it tries to define the country for map searches using the Activity.Locale attribute:

                try
                {
                    var cultureInfo = new RegionInfo(sc.Context.Activity.Locale);
                    country = cultureInfo.TwoLetterISORegionName;
                }
                catch (Exception)
                {
                    // Default to everything if we can't restrict the country
                }

This country variable is later used in the GetLocationsByFuzzyQueryAsync call.

This doesn't work well if the user has its locale set to en-US and is currently located in Germany for example. If I say, "find a starbucks near me" while in germany, I'll get starbucks in US, not where I am. 

**To Reproduce**

1. Ensure your locale is set to en-US.
2. Say "Find a starbucks near me" in the proper language while in Germany, Spain or any other supported langague using the en-US locale.
3. You will only get starbucks in the US

**Expected behavior**
I would expect POI to use my current location (lat and long) and not my locale to determine my country and run Azure Map searches.

**Comment by darrenj** [comment]
@gabog I looked into this

US is there as a backup only if locale isn't provided, we could remove this and then generate an error that Locale isn't set which isn't exactly the best experience - it's a worst case scenario and we can look at it.

As for locale, the maps API strongly recommends providing a country to limit the results otherwise we observed you got slightly odd results from time to time. Setting country limits this.

```
The basic default API is Free Form Search which handles the most fuzzy of inputs handling any combination of address or POI tokens. This search API is the canonical 'single line search'. The Free Form Search API is a seamless combination of POI search and geocoding. The API can also be weighted with a contextual position (lat./lon. pair), or fully constrained by a coordinate and radius, or it can be executed more generally without any geo biasing anchor point.

We strongly advise you to use the 'countrySet' parameter to specify only the countries for which your application needs coverage, as the default behavior will be to search the entire world, potentially returning unnecessary results.
https://docs.microsoft.com/en-gb/rest/api/maps/search
```

However it might well be best that we do a reverse summary to get the country from the provided lat long (assume you are providing this through the IPA.Location event). This would likely make more sense to perform when VA receives the IPA.Location event to avoid having to perform an extra call each and every time.

Alternatively we could push this burden onto the client (e.g. IPA.Location.Country) event or something in the user-store but this doesn't get around your traveling situation.

We can remove country from the parameter as a short-term issue but you should then expect search results that might be slightly wrong (lat/long) - that said the radius parameter may enable us to further constrain and avoid this.

@ryanlengel In Vanadium can you do a quick experiment with radius (controllable through a new configuration setting) to see if it avoids the issue that providing country resolved?

**Comment by gabog** [comment]
I agree with providing country to the maps API, but I think this should be inferred from the user’s provided location as you say and not out of locale. I wasn’t able to get any meaningful results while in Germany when the locale was set to en-US.

Gabo

**Comment by ryanisgrig** [comment]
We also need to consider if we'll use an entity from the onboarding dialog. There was a lot of feedback after our recent bug bash that when the both asks for location in the onboarding sample we should recognize that location and use it as the default POI. To my count, we have 3 suggestions as to where POI should get the location from.

* Location event
* Bot Activity locale
* Onboarding dialog location
