### ISSUE TITLE
[Enterprise Bot Template][C#] How to use the EnterpriseDialog / InterruptableDialog properly?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#539]
I'm building a bot based on the Enterprise Bot Template that lets users do tasks with our Azure DevOps tenant. One of the Dialogs we made is the `CreateProjectDialog` (based upon the `OnboardingDialog`) that is triggered by a `CreateProject` intent in LUIS.

I have two issues with the `EnterpriseDialog` / `InterruptableDialog` classes:

1. Unintended interruptions:

Most of it works fine, but inside the `CreateProjectDialog`, the dispatcher will still tear the user out of the dialog's flow if it thinks the user's answer should be processed by another part. E.g. when the bot asks:

> Please enter a project name

The user can reply with a project name containing the words `exit` or `help` (say the user enters the project name `help the children`) and then the user inadvertently triggers the `Cancel` and `Help` and `Next` intents, even though he or she was just filling out a list of questions.

I suppose I would need to override the `OnHelp` and `OnCancel` methods, but it's unclear to me what the best practice is do that.

2. How to perform an action **after** the interruption?

When a user cancels, I want to clear the dialog state. However, `OnCancel` is called **before** the `CancelDialog` dialog, while I only want to clear the dialog state **after the user confirms the cancelation**

Any guidance on this would be greatly appreciated!

**Comment by lauren-mills** [comment]
Hi @hansmbakker, if the cancel and help interruptions as they are will interfere with your specific use case, there are a couple of solutions. You can train the intents in the General model more to optimize for your scenario, you can increase the score threshold in the OnInterruptDialogAsync method to only trigger the OnCancel and OnHelp when the intent score is very high, or in your CreateProjectDialog you can inherit from ComponentDialog directly to circumvent the EnterpriseDialog since it is there you show example interruptions.

For your second question, this logic should go into the CancelDialog in the EndComponentAsync method. You'll see in that this method handles user's response to the cancel prompt. You can add your state-clearing logic there.

**Comment by hansmbakker** [comment]
Hi @lauren-mills, thank you for your explanation.

The first part I understand. As for the second part (putting logic in CancelDialog) I would expect some generic code in the CancelDialog since I believe that should be a generic dialog? Maybe it would be useful to make it part of the template?

**Comment by lauren-mills** [comment]
I will add a task to explore adding in state-clearing to the CancelDialog. My initial thought is that each bot will have a unique state story, and clearing everything may not make sense in every case, but it might be good to include as an example.

**Comment by hansmbakker** [comment]
I agree, so the CancelDialog should not have to clean everything itself, but it would be nice to have some kind of signal to the originating dialog to know that the dialog was indeed canceled. Reacting on that, the dialog could clear its own state.
