### ISSUE TITLE
[POI] Saying "Option X" to get directions does not work

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#572]
**Project**
Skills

**Description**
When a POI card is displayed a user, if they say "go to option X" (like the card says) the Virtual Assistant will not understand what to do. 

**To Reproduce**
1. Launch POI scenario
2. Type or say a number to select that option.
3. Virtual Assistant will not understand what to route to.

**Expected behavior**
1. Launch POI scenario
2. Type or say a number to select that option.
3. Virtual Assistant will route to that option.

**Additional context**
This is because it is displaying a mock up Adaptive Card but does not have this functionality. 

Utilize the number entity like Email skill.

- [ ] Use a ChoicePrompt to pick up number or ordinal
- [ ] Test "Option 1"
- [ ] Test "First one"

**Comment by darrenj** [comment]
I'm investigating adding this to the automotive skills and ensure we have a generalised approach we can add to a skills developer guide

**Comment by darrenj** [comment]
@ryanlengel This doesn't appear to work? I suspect because the dialog is being torn down and because we don't use a ChoicePrompt (like in the Automotive Skill for instance). If we use this type of prompt you can say first one, second one, 0, 1, etc.  This is really critical for the speech scenarios we wiring in now.

You can then leverage Marion's GetSpeakableOptions technique too instead of the approach I have in PR right now as a temporary improvement on speech capabilities.

![image](https://user-images.githubusercontent.com/33519520/53422827-20f29a00-39d8-11e9-92c8-51bdc8fed47a.png)

![image](https://user-images.githubusercontent.com/33519520/53422867-35cf2d80-39d8-11e9-8de2-7a990b2ab376.png)

**Comment by ryanisgrig** [comment]
I see - this worked before when the POI LU model had 10k utterances, probably becaues it was just always weighing in POI's favor. The tests didn't pick up the change because the LUIS recognizer is mocked and coded in.

Switching to the Choice Prompt. does the LUIS model need ordinal/number entities or is that just picked up in the prompt? I see the Automotive Skill has the number phrase list but that seems to be it.

**Comment by ryanisgrig** [comment]
I like the `GetSpeakableOptions` approach as well.

**Comment by darrenj** [comment]
Picked up in the prompt 😊  One thing I know isn't working (and I'll raise the bug now is "last one") but other combinations work quite nicely. This will likely then "fix" the zero based issue thing I had to do earlier which you can remove as needed when merged
