### ISSUE TITLE
After Login Nothing Happening

### ISSUE THREAD

**Issue by ckalgos** [microsoft/botframework-solutions#713]
![testbot](https://user-images.githubusercontent.com/32110271/52343726-e9c74380-2a3e-11e9-876e-088112a0c971.png)

In above screen shot if i click on Login , login page pop up comes , once i enter the details the pop up is closed but nothing is happening, if a enter something after that AuthPromptValidator is called with token as null

**Comment by saravana13** [comment]
![testbot](https://user-images.githubusercontent.com/32110271/52343726-e9c74380-2a3e-11e9-876e-088112a0c971.png)

In above screen shot if i click on Login , login page pop up comes , once i enter the details the pop up is closed but nothing is happening, if a enter something after that AuthPromptValidator is called with token as null

**Comment by Zerryth** [comment]
Investigating now...

**Comment by Zerryth** [comment]
@saravana13, this happens when ngrok is not configured in the emulator.

The token gets sent back to the bot from the authentication service in Azure, so if you want the login to work locally, ngrok needs to be configured for that service to send back the token.

To add ngrok to the Bot Framework Emulator, click the bottom-right corner gear to get to Emulator Settings
![image](https://user-images.githubusercontent.com/35248895/53043186-cd62d800-343c-11e9-989d-670c78afd514.png)

Then in "Path to ngrok", click the Browse button to where you have ngrok installed. (You can download ngrok [here ](https://ngrok.com/download)if you don't have it already).
![image](https://user-images.githubusercontent.com/35248895/53043291-000cd080-343d-11e9-993f-c0ce0ae2f313.png)

**Comment by Zerryth** [comment]
@ryanlengel tagging you as requested to update VA docs to mention this for new users :)

removing Support label

**Comment by balikpinoy** [comment]
I have a similar issue.
I am using Auth0 as my service.  Everything works in DEV using bot emulator.  Everything works on PROD using bot emulator.
However, when I use a web chat connected via directline, after I enter the 6 digit validation code, nothing happens.  No Error.
I think I've traced it to the FinishLoginDialog not getting invoked after entering the 6 digit code, and its just getting processed as a message with a status of waiting.
I can replicate the issue if I don't enter the correct code when testing on the bot emulator on DEV and PROD.
Any insights on this?  Thanks!

**Comment by ryanisgrig** [comment]
Closing this issue, docs take care of this.

@balikpinoy if you still have this issue please open a new one, I don't think it's related. Thanks!

**Comment by lshade** [comment]
@ryanlengel I'm having the same issue @balikpinoy described. Is there a solution for this? Thank you

**Comment by ryanisgrig** [comment]
@lshade please open a new issue with your description and we can get it triaged. Thanks!

**Comment by samaea** [comment]
> @ryanlengel I'm having the same issue @balikpinoy described. Is there a solution for this? Thank you

What Zerryth commented on 19 Feb above resolved my issue. However, once you point the emulator to the ngrok.exe file, I also had to tick the checkbox that states "_Run ngrok when the Emulator starts up_" as shown in the screenshot below. You might have to close and re-open the emulator, but you know ngrok is working, once the message about ngrok not being configured goes away. Not sure if that will help resolve your issue, but worth a shot.

![ngrok](https://user-images.githubusercontent.com/32162601/59541974-a6547880-8efb-11e9-945c-f19f86a78b50.png)

![ngrok-working](https://user-images.githubusercontent.com/32162601/59542078-09460f80-8efc-11e9-8e2b-7976ae60aaf2.png)

Hope that helps!
