### ISSUE TITLE
[VA Template] Active Learning

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#754]
**Is your feature request related to a problem? Please describe.**
QnA Maker made [Active Learning](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/improve-knowledge-base) available. This allows to offer suggested questions to the user if QnA Maker is not certain, and to learn from the question feedback that the user gave.

There is an example implementation available (but without Telemetry integration) at https://github.com/Microsoft/BotBuilder-Samples/blob/master/experimental/csharp_dotnetcore/qnamaker-activelearning-bot/

The Enterprise Bot Template (`TelemetryQnAMaker` class) does not make use of this functionality yet.

**Describe the solution you'd like**
Integration of Active Learning in `TelemetryQnAMaker` class

**Describe alternatives you've considered**
Write it myself.

**Comment by saurav2107** [comment]
Hey team, is there any documentation on how to achieve active learning for QnA in Enterprise Bot template?

**Comment by lauren-mills** [comment]
Hi @saurav2107 we don't have any documentation specific to the enterprise template, but there is a bot sample available here that can be modified to enable the scenario: https://github.com/Microsoft/BotBuilder-Samples/tree/master/experimental/csharp_dotnetcore/qnamaker-activelearning-bot

It looks like this dialog code would do the job: https://github.com/Microsoft/BotBuilder-Samples/blob/master/experimental/csharp_dotnetcore/qnamaker-activelearning-bot/Helpers/DialogHelper.cs

You can replace the qna logic in MainDialog.cs with a BeginDialog() call to this dialog. If you get something working feel free to make a PR!

**Comment by JackStrap** [comment]
Hi @saurav2107 I was able to add active learning for QnA in Enterprise Bot Template.
You can check it at this address : [https://devbolsewebbot.azurewebsites.net/](https://devbolsewebbot.azurewebsites.net/)
To make it work i created a folder "QnA" under Dialogs and i copy, rename the files from the experimental project. The files that we need are under the Helpers folder.
I copy the two FeedbackRecord.cs in my QnA folder
I rename CardHelper.cs to QnACard.cs
I rename DialogHelper.cs to QnADialog.cs
I rename ActiveLearningHelper.cs to QnAResponses.cs
After renaming the files, you go to MainDialog.cs and add the new dialog: AddDialog(new QnADialog("your Bot Service", "your QnaMakerKey")) and since i didn't need all the Luis stuffs from the enterprise template, i remove them from the RouteAsync method and i put the QnaDialog in it like this :
await dc.BeginDialogAsync(nameof(QnADialog), _qnaMakerOptions);
I will try to put my code on GitHub in the next few days.

Hope it can help you.

**Comment by darrenj** [comment]
SDK will be updated to support additional QnAMaker capabilities
