### ISSUE TITLE
[VA] Onboarding dialog example is confusing to new users

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#756]
**Is your feature request related to a problem? Please describe.**

Based on outcomes from the hackathon, new users are confused at the functionality of the onboarding dialog when starting a conversation with a new user id. The VA asks for a name and location, but these responses are not used elsewhere. Additionally, it becomes cumbersome when testing new scenarios and having to repeat these questions each time.

**Describe the solution you'd like**

Considering that the onboarding dialog is meant from demonstration, when there is a new user I suggest showing the standard introduction card but including a button that can trigger the onboarding dialog. If someone wants to demo onboarding, they can select the button and go through the steps. Otherwise, they will only be greeting with a single bot response and can begin their testing/demoing.

**Describe alternatives you've considered**

The state from onboarding dialog is referenced in subsequent skills, so they know a user's name and their location. This requires the skills to have a dependency of the VA project and assuming that state information is available.

**Additional context**

**Comment by gabog** [comment]
I agree, due to how the emulator works, the onboarding dialog shows way too often during dev and we normally comment it out early on. If we keep it, it may be good to use the state generated by the onboarding dialog in the "demo skill" we talked about yesterday so it can be easily removed and doesn't affect the other skills don't need the data collected by the demo onboarding dialog.
