### ISSUE TITLE
As a developer, I would like it if IBotTelemetryClient would pass ITurnContext to the Track* methods in I IBotTelemetryClient so I can add custom telemetry attributes based on the Turn context.

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#762]
We have a need to augment the telemetry data with turn Related information (active user, channeldata, etc,) being logged beyond what's provide out of box by VA and BF

**Describe the solution you'd like**
I would like have an ITurnContext parameter with the current TurnContext instance in the virtual methods defined in IBotTelemetryClient so I augment the properties and metrics being logged as needed.

**Describe alternatives you've considered**
NA

**Additional context**
We need an extensibility approach to telemetry so we can add custom properties and metrics that are not provided in the OOTB telemetry. ITurnContext, will give us additional information on the Turn, activity and current user so we can also apply business rules (GDPR and others) to the data being logged.

**Comment by garypretty** [comment]
This would certainly solve a problem I am facing right now in terms of ensuring certain sensitive data is not captured via telemetry.

**Comment by ryanisgrig** [comment]
@daveta FYI

**Comment by daveta** [comment]
Hi Gabo, Instead of the ITurnContext, what about passing the Activity instead?  

It seems like there are two primary sources of data that you may want to log from: The Activity data and custom storage properties.  

By providing only the Activity, if you need to resolve data from storage, the activity provides all the information necessary to resolve storage records (at user/context levels) since you can derive the storage key.  So, the activity appears to be the lowest concept we could provide, without tightly coupling to any framework concepts.

Thoughts?

**Comment by gabog** [comment]
Hi, in my use case, the activity won't be enough. We store privacy preferences for the user making the request in state and TurnContext gives us access to that info, the Activity doesn't have it. 
Makes sense?

**Comment by daveta** [comment]
Makes sense, there's no way to get to storage without the turn context.  We're looking at addressing some other issues there, we'll have to address this in the 4.4 timeframe.
