### ISSUE TITLE
.\update_published_models.ps1 "en-us" generates GeneralLU.cs under assistant\Dialogs\Shared\Resources

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#786]
**Project**
Virtual Assistant

**Description**
Hi @lauren-mills, I just pulled the latest and when I run update_published_models.ps1, I noticed that it generates a GeneralLUI.cs under assistant\Dialogs\Shared\Resources, shouldn't that be generated in the Solutions project? 
![image](https://user-images.githubusercontent.com/12264946/52768075-5bccf900-2ffa-11e9-8f5e-e3bf21f036cf.png)

**To Reproduce**
1. Pull the latest and run .\update_published_models.ps1 "en-us" 

**Expected behavior**
Not sure but I think the generalLU.cs should be generated in the Solutions project.

**Comment by lauren-mills** [comment]
As we discussed, the Microsoft.Bot.Solutions project will be moving to nuget soon. And since the general.cs class needs to be accessed by all the skills we will be putting it in the nuget as well, so users won’t be able to update it. The GeneralLU.cs was generated by the same logic as the others. I’m still trying to decide how to handle it, but I didn’t want to add custom logic to the script to omit it.

**Comment by gabog** [comment]
Ah, OK.
