### ISSUE TITLE
P2: Standardize inputhint usage or use default BotBuilder settings

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#83]
- [x] Review Calendar skill
- [x] Review Email skill
- [x] Review Todo skill
- [x] Review POI skill

**Comment by ryanisgrig** [comment]
[Per documentation](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0):
If you do not set the input hint for a message, the Bot Builder SDK will automatically set it for you by using this logic:
* If your bot sends a prompt, the input hint for the message will specify that your bot is **expecting input**.
* If your bot sends single message, the input hint for the message will specify that your bot is **accepting input**.
* If your bot sends a series of consecutive messages, the input hint for all but the final message in the series will specify that your bot is **ignoring input**, and the input hint for the final message in the series will specify that your bot is **accepting input**.

Because we are using a template manager for VA resources, if left blank the SDK does not add on the appropriate input hints. I'll apply the following to our resources:
1. If consecutive messages are sent from the VA, the input hint for all but the final message will be **ignoring input**.
2. If the final message is part of a multi-turn dialog, it will be **expecting input** to allow a user to naturally carry on the conversation: *"Pick the first one."*
3. If the final message is as the end of a dialog, it will be **accepting input** to allow the microphone to be accessible. This is a good opportunity to allow for wake word to effectively allow a user to complete a dialog and then wake up the bot again with *"Assistant, now do this."*

**Comment by ryanisgrig** [comment]
Reviewed all skills and they are set up correctly - there was another issue with exception messages having an incorrect input hint that is resolved
