### ISSUE TITLE
What SDLC is applied to Enterprise Bot Template vs Enterprise BotSample?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#965]
## Project

**Name**: Enterprise Bot Template

**Language**: C#

## Description
It is unclear to me how Enterprise Bot Template and Enterprise Bot Sample are related to each other.

I see that e.g. https://github.com/Microsoft/AI/pull/692 is applied to the template but this fix did not make it into the bot sample.

## Expected behavior
I would expect that fixes are done in the template and that the sample is updated based on the template

**Comment by lauren-mills** [comment]
The sample is meant to be an instance of the latest template that users can look at if they have already deployed an older version. This discrepancy is an oversight, and I'll try to fix it in the next week or so as time permits. Thanks

**Comment by ericchansen** [comment]
Suppose that we want to be able to pull upstream commits using Git and something like [subtree](https://stackoverflow.com/questions/24577084/forking-a-sub-directory-of-a-repository-on-github-and-making-it-part-of-my-own-r?noredirect=1&lq=1) (rather than use the .vsix template). Should we base our project off the sample or template directory?
